name: console
description: Riverly console web app powered by TanStack
runtime:
  name: nodejs
  options:
    packagemanager: bun
config:
  pulumi:tags:
    value:
      team: console

gcp:region:
  value: us-central1
