/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as GithubInstalledRouteImport } from './routes/github/installed'
import { Route as AuthSlugRouteRouteImport } from './routes/_auth/$slug/route'
import { Route as ApiSyncV1RouteImport } from './routes/api/sync/v1'
import { Route as ApiGithubReposRouteImport } from './routes/api/github.repos'
import { Route as ApiGithubInstallsRouteImport } from './routes/api/github.installs'
import { Route as ApiGithubCallbackRouteImport } from './routes/api/github.callback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthSlugDashRouteRouteImport } from './routes/_auth/$slug/_dash/route'
import { Route as AuthSlugDashIndexRouteImport } from './routes/_auth/$slug/_dash/index'
import { Route as ApiServersServerIdReadmeRouteImport } from './routes/api/servers/$serverId.readme'
import { Route as AuthSlugDashSettingsRouteRouteImport } from './routes/_auth/$slug/_dash/settings/route'
import { Route as AuthSlugDashDeploymentsRouteRouteImport } from './routes/_auth/$slug/_dash/deployments/route'
import { Route as AuthSlugDashSettingsIndexRouteImport } from './routes/_auth/$slug/_dash/settings/index'
import { Route as AuthSlugDashDeploymentsIndexRouteImport } from './routes/_auth/$slug/_dash/deployments/index'
import { Route as AuthSlugDashSettingsWebhooksRouteImport } from './routes/_auth/$slug/_dash/settings/webhooks'
import { Route as AuthSlugDashSettingsGithubRouteImport } from './routes/_auth/$slug/_dash/settings/github'
import { Route as AuthSlugDashServersNewRouteImport } from './routes/_auth/$slug/_dash/servers/new'
import { Route as AuthSlugDashServersImportRouteImport } from './routes/_auth/$slug/_dash/servers/import'
import { Route as AuthSlugDashDeploymentsProductionRouteImport } from './routes/_auth/$slug/_dash/deployments/production'
import { Route as AuthSlugDashDeploymentsPreviewRouteImport } from './routes/_auth/$slug/_dash/deployments/preview'
import { Route as AuthSlugDashServersListRouteRouteImport } from './routes/_auth/$slug/_dash/servers/_list/route'
import { Route as AuthSlugDashServersServerIdRouteRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/route'
import { Route as AuthSlugDashDeploymentsDeploymentIdRouteRouteImport } from './routes/_auth/$slug/_dash/deployments/$deploymentId/route'
import { Route as AuthSlugDashServersListIndexRouteImport } from './routes/_auth/$slug/_dash/servers/_list/index'
import { Route as AuthSlugDashServersServerIdIndexRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/index'
import { Route as AuthSlugDashDeploymentsDeploymentIdIndexRouteImport } from './routes/_auth/$slug/_dash/deployments/$deploymentId/index'
import { Route as AuthSlugDashServersListPublicRouteImport } from './routes/_auth/$slug/_dash/servers/_list/public'
import { Route as AuthSlugDashServersListPrivateRouteImport } from './routes/_auth/$slug/_dash/servers/_list/private'
import { Route as AuthSlugDashServersServerIdSettingsRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/settings'
import { Route as AuthSlugDashServersServerIdReadmeRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/readme'
import { Route as AuthSlugDashServersServerIdDeployRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/deploy'
import { Route as AuthSlugDashServersServerIdAnalyticsRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/analytics'
import { Route as AuthSlugDashDeploymentsDeploymentIdLogsRouteImport } from './routes/_auth/$slug/_dash/deployments/$deploymentId/logs'
import { Route as AuthSlugDashServersServerIdDeploymentsRouteRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/deployments/route'
import { Route as AuthSlugDashServersServerIdDeploymentsIndexRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/deployments/index'
import { Route as AuthSlugDashServersServerIdDeploymentsProductionRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/deployments/production'
import { Route as AuthSlugDashServersServerIdDeploymentsPreviewRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/deployments/preview'

const AuthSlugDashServersRouteImport = createFileRoute(
  '/_auth/$slug/_dash/servers',
)()

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const GithubInstalledRoute = GithubInstalledRouteImport.update({
  id: '/github/installed',
  path: '/github/installed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSlugRouteRoute = AuthSlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiSyncV1Route = ApiSyncV1RouteImport.update({
  id: '/api/sync/v1',
  path: '/api/sync/v1',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubReposRoute = ApiGithubReposRouteImport.update({
  id: '/api/github/repos',
  path: '/api/github/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubInstallsRoute = ApiGithubInstallsRouteImport.update({
  id: '/api/github/installs',
  path: '/api/github/installs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCallbackRoute = ApiGithubCallbackRouteImport.update({
  id: '/api/github/callback',
  path: '/api/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSlugDashRouteRoute = AuthSlugDashRouteRouteImport.update({
  id: '/_dash',
  getParentRoute: () => AuthSlugRouteRoute,
} as any)
const AuthSlugDashServersRoute = AuthSlugDashServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AuthSlugDashRouteRoute,
} as any)
const AuthSlugDashIndexRoute = AuthSlugDashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSlugDashRouteRoute,
} as any)
const ApiServersServerIdReadmeRoute =
  ApiServersServerIdReadmeRouteImport.update({
    id: '/api/servers/$serverId/readme',
    path: '/api/servers/$serverId/readme',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSlugDashSettingsRouteRoute =
  AuthSlugDashSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthSlugDashRouteRoute,
  } as any)
const AuthSlugDashDeploymentsRouteRoute =
  AuthSlugDashDeploymentsRouteRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AuthSlugDashRouteRoute,
  } as any)
const AuthSlugDashSettingsIndexRoute =
  AuthSlugDashSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthSlugDashSettingsRouteRoute,
  } as any)
const AuthSlugDashDeploymentsIndexRoute =
  AuthSlugDashDeploymentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthSlugDashDeploymentsRouteRoute,
  } as any)
const AuthSlugDashSettingsWebhooksRoute =
  AuthSlugDashSettingsWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthSlugDashSettingsRouteRoute,
  } as any)
const AuthSlugDashSettingsGithubRoute =
  AuthSlugDashSettingsGithubRouteImport.update({
    id: '/github',
    path: '/github',
    getParentRoute: () => AuthSlugDashSettingsRouteRoute,
  } as any)
const AuthSlugDashServersNewRoute = AuthSlugDashServersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthSlugDashServersRoute,
} as any)
const AuthSlugDashServersImportRoute =
  AuthSlugDashServersImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthSlugDashServersRoute,
  } as any)
const AuthSlugDashDeploymentsProductionRoute =
  AuthSlugDashDeploymentsProductionRouteImport.update({
    id: '/production',
    path: '/production',
    getParentRoute: () => AuthSlugDashDeploymentsRouteRoute,
  } as any)
const AuthSlugDashDeploymentsPreviewRoute =
  AuthSlugDashDeploymentsPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AuthSlugDashDeploymentsRouteRoute,
  } as any)
const AuthSlugDashServersListRouteRoute =
  AuthSlugDashServersListRouteRouteImport.update({
    id: '/_list',
    getParentRoute: () => AuthSlugDashServersRoute,
  } as any)
const AuthSlugDashServersServerIdRouteRoute =
  AuthSlugDashServersServerIdRouteRouteImport.update({
    id: '/servers/$serverId',
    path: '/servers/$serverId',
    getParentRoute: () => AuthSlugDashRouteRoute,
  } as any)
const AuthSlugDashDeploymentsDeploymentIdRouteRoute =
  AuthSlugDashDeploymentsDeploymentIdRouteRouteImport.update({
    id: '/$deploymentId',
    path: '/$deploymentId',
    getParentRoute: () => AuthSlugDashDeploymentsRouteRoute,
  } as any)
const AuthSlugDashServersListIndexRoute =
  AuthSlugDashServersListIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthSlugDashServersListRouteRoute,
  } as any)
const AuthSlugDashServersServerIdIndexRoute =
  AuthSlugDashServersServerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthSlugDashServersServerIdRouteRoute,
  } as any)
const AuthSlugDashDeploymentsDeploymentIdIndexRoute =
  AuthSlugDashDeploymentsDeploymentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthSlugDashDeploymentsDeploymentIdRouteRoute,
  } as any)
const AuthSlugDashServersListPublicRoute =
  AuthSlugDashServersListPublicRouteImport.update({
    id: '/public',
    path: '/public',
    getParentRoute: () => AuthSlugDashServersListRouteRoute,
  } as any)
const AuthSlugDashServersListPrivateRoute =
  AuthSlugDashServersListPrivateRouteImport.update({
    id: '/private',
    path: '/private',
    getParentRoute: () => AuthSlugDashServersListRouteRoute,
  } as any)
const AuthSlugDashServersServerIdSettingsRoute =
  AuthSlugDashServersServerIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthSlugDashServersServerIdRouteRoute,
  } as any)
const AuthSlugDashServersServerIdReadmeRoute =
  AuthSlugDashServersServerIdReadmeRouteImport.update({
    id: '/readme',
    path: '/readme',
    getParentRoute: () => AuthSlugDashServersServerIdRouteRoute,
  } as any)
const AuthSlugDashServersServerIdDeployRoute =
  AuthSlugDashServersServerIdDeployRouteImport.update({
    id: '/deploy',
    path: '/deploy',
    getParentRoute: () => AuthSlugDashServersServerIdRouteRoute,
  } as any)
const AuthSlugDashServersServerIdAnalyticsRoute =
  AuthSlugDashServersServerIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthSlugDashServersServerIdRouteRoute,
  } as any)
const AuthSlugDashDeploymentsDeploymentIdLogsRoute =
  AuthSlugDashDeploymentsDeploymentIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthSlugDashDeploymentsDeploymentIdRouteRoute,
  } as any)
const AuthSlugDashServersServerIdDeploymentsRouteRoute =
  AuthSlugDashServersServerIdDeploymentsRouteRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AuthSlugDashServersServerIdRouteRoute,
  } as any)
const AuthSlugDashServersServerIdDeploymentsIndexRoute =
  AuthSlugDashServersServerIdDeploymentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthSlugDashServersServerIdDeploymentsRouteRoute,
  } as any)
const AuthSlugDashServersServerIdDeploymentsProductionRoute =
  AuthSlugDashServersServerIdDeploymentsProductionRouteImport.update({
    id: '/production',
    path: '/production',
    getParentRoute: () => AuthSlugDashServersServerIdDeploymentsRouteRoute,
  } as any)
const AuthSlugDashServersServerIdDeploymentsPreviewRoute =
  AuthSlugDashServersServerIdDeploymentsPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AuthSlugDashServersServerIdDeploymentsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/$slug': typeof AuthSlugDashRouteRouteWithChildren
  '/github/installed': typeof GithubInstalledRoute
  '/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/installs': typeof ApiGithubInstallsRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/sync/v1': typeof ApiSyncV1Route
  '/$slug/deployments': typeof AuthSlugDashDeploymentsRouteRouteWithChildren
  '/$slug/settings': typeof AuthSlugDashSettingsRouteRouteWithChildren
  '/api/servers/$serverId/readme': typeof ApiServersServerIdReadmeRoute
  '/$slug/': typeof AuthSlugDashIndexRoute
  '/$slug/deployments/$deploymentId': typeof AuthSlugDashDeploymentsDeploymentIdRouteRouteWithChildren
  '/$slug/servers/$serverId': typeof AuthSlugDashServersServerIdRouteRouteWithChildren
  '/$slug/servers': typeof AuthSlugDashServersListRouteRouteWithChildren
  '/$slug/deployments/preview': typeof AuthSlugDashDeploymentsPreviewRoute
  '/$slug/deployments/production': typeof AuthSlugDashDeploymentsProductionRoute
  '/$slug/servers/import': typeof AuthSlugDashServersImportRoute
  '/$slug/servers/new': typeof AuthSlugDashServersNewRoute
  '/$slug/settings/github': typeof AuthSlugDashSettingsGithubRoute
  '/$slug/settings/webhooks': typeof AuthSlugDashSettingsWebhooksRoute
  '/$slug/deployments/': typeof AuthSlugDashDeploymentsIndexRoute
  '/$slug/settings/': typeof AuthSlugDashSettingsIndexRoute
  '/$slug/servers/$serverId/deployments': typeof AuthSlugDashServersServerIdDeploymentsRouteRouteWithChildren
  '/$slug/deployments/$deploymentId/logs': typeof AuthSlugDashDeploymentsDeploymentIdLogsRoute
  '/$slug/servers/$serverId/analytics': typeof AuthSlugDashServersServerIdAnalyticsRoute
  '/$slug/servers/$serverId/deploy': typeof AuthSlugDashServersServerIdDeployRoute
  '/$slug/servers/$serverId/readme': typeof AuthSlugDashServersServerIdReadmeRoute
  '/$slug/servers/$serverId/settings': typeof AuthSlugDashServersServerIdSettingsRoute
  '/$slug/servers/private': typeof AuthSlugDashServersListPrivateRoute
  '/$slug/servers/public': typeof AuthSlugDashServersListPublicRoute
  '/$slug/deployments/$deploymentId/': typeof AuthSlugDashDeploymentsDeploymentIdIndexRoute
  '/$slug/servers/$serverId/': typeof AuthSlugDashServersServerIdIndexRoute
  '/$slug/servers/': typeof AuthSlugDashServersListIndexRoute
  '/$slug/servers/$serverId/deployments/preview': typeof AuthSlugDashServersServerIdDeploymentsPreviewRoute
  '/$slug/servers/$serverId/deployments/production': typeof AuthSlugDashServersServerIdDeploymentsProductionRoute
  '/$slug/servers/$serverId/deployments/': typeof AuthSlugDashServersServerIdDeploymentsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$slug': typeof AuthSlugDashIndexRoute
  '/github/installed': typeof GithubInstalledRoute
  '/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/installs': typeof ApiGithubInstallsRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/sync/v1': typeof ApiSyncV1Route
  '/api/servers/$serverId/readme': typeof ApiServersServerIdReadmeRoute
  '/$slug/servers': typeof AuthSlugDashServersListIndexRoute
  '/$slug/deployments/preview': typeof AuthSlugDashDeploymentsPreviewRoute
  '/$slug/deployments/production': typeof AuthSlugDashDeploymentsProductionRoute
  '/$slug/servers/import': typeof AuthSlugDashServersImportRoute
  '/$slug/servers/new': typeof AuthSlugDashServersNewRoute
  '/$slug/settings/github': typeof AuthSlugDashSettingsGithubRoute
  '/$slug/settings/webhooks': typeof AuthSlugDashSettingsWebhooksRoute
  '/$slug/deployments': typeof AuthSlugDashDeploymentsIndexRoute
  '/$slug/settings': typeof AuthSlugDashSettingsIndexRoute
  '/$slug/deployments/$deploymentId/logs': typeof AuthSlugDashDeploymentsDeploymentIdLogsRoute
  '/$slug/servers/$serverId/analytics': typeof AuthSlugDashServersServerIdAnalyticsRoute
  '/$slug/servers/$serverId/deploy': typeof AuthSlugDashServersServerIdDeployRoute
  '/$slug/servers/$serverId/readme': typeof AuthSlugDashServersServerIdReadmeRoute
  '/$slug/servers/$serverId/settings': typeof AuthSlugDashServersServerIdSettingsRoute
  '/$slug/servers/private': typeof AuthSlugDashServersListPrivateRoute
  '/$slug/servers/public': typeof AuthSlugDashServersListPublicRoute
  '/$slug/deployments/$deploymentId': typeof AuthSlugDashDeploymentsDeploymentIdIndexRoute
  '/$slug/servers/$serverId': typeof AuthSlugDashServersServerIdIndexRoute
  '/$slug/servers/$serverId/deployments/preview': typeof AuthSlugDashServersServerIdDeploymentsPreviewRoute
  '/$slug/servers/$serverId/deployments/production': typeof AuthSlugDashServersServerIdDeploymentsProductionRoute
  '/$slug/servers/$serverId/deployments': typeof AuthSlugDashServersServerIdDeploymentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/$slug': typeof AuthSlugRouteRouteWithChildren
  '/github/installed': typeof GithubInstalledRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/$slug/_dash': typeof AuthSlugDashRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/installs': typeof ApiGithubInstallsRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/sync/v1': typeof ApiSyncV1Route
  '/_auth/$slug/_dash/deployments': typeof AuthSlugDashDeploymentsRouteRouteWithChildren
  '/_auth/$slug/_dash/settings': typeof AuthSlugDashSettingsRouteRouteWithChildren
  '/api/servers/$serverId/readme': typeof ApiServersServerIdReadmeRoute
  '/_auth/$slug/_dash/': typeof AuthSlugDashIndexRoute
  '/_auth/$slug/_dash/deployments/$deploymentId': typeof AuthSlugDashDeploymentsDeploymentIdRouteRouteWithChildren
  '/_auth/$slug/_dash/servers/$serverId': typeof AuthSlugDashServersServerIdRouteRouteWithChildren
  '/_auth/$slug/_dash/servers': typeof AuthSlugDashServersRouteWithChildren
  '/_auth/$slug/_dash/servers/_list': typeof AuthSlugDashServersListRouteRouteWithChildren
  '/_auth/$slug/_dash/deployments/preview': typeof AuthSlugDashDeploymentsPreviewRoute
  '/_auth/$slug/_dash/deployments/production': typeof AuthSlugDashDeploymentsProductionRoute
  '/_auth/$slug/_dash/servers/import': typeof AuthSlugDashServersImportRoute
  '/_auth/$slug/_dash/servers/new': typeof AuthSlugDashServersNewRoute
  '/_auth/$slug/_dash/settings/github': typeof AuthSlugDashSettingsGithubRoute
  '/_auth/$slug/_dash/settings/webhooks': typeof AuthSlugDashSettingsWebhooksRoute
  '/_auth/$slug/_dash/deployments/': typeof AuthSlugDashDeploymentsIndexRoute
  '/_auth/$slug/_dash/settings/': typeof AuthSlugDashSettingsIndexRoute
  '/_auth/$slug/_dash/servers/$serverId/deployments': typeof AuthSlugDashServersServerIdDeploymentsRouteRouteWithChildren
  '/_auth/$slug/_dash/deployments/$deploymentId/logs': typeof AuthSlugDashDeploymentsDeploymentIdLogsRoute
  '/_auth/$slug/_dash/servers/$serverId/analytics': typeof AuthSlugDashServersServerIdAnalyticsRoute
  '/_auth/$slug/_dash/servers/$serverId/deploy': typeof AuthSlugDashServersServerIdDeployRoute
  '/_auth/$slug/_dash/servers/$serverId/readme': typeof AuthSlugDashServersServerIdReadmeRoute
  '/_auth/$slug/_dash/servers/$serverId/settings': typeof AuthSlugDashServersServerIdSettingsRoute
  '/_auth/$slug/_dash/servers/_list/private': typeof AuthSlugDashServersListPrivateRoute
  '/_auth/$slug/_dash/servers/_list/public': typeof AuthSlugDashServersListPublicRoute
  '/_auth/$slug/_dash/deployments/$deploymentId/': typeof AuthSlugDashDeploymentsDeploymentIdIndexRoute
  '/_auth/$slug/_dash/servers/$serverId/': typeof AuthSlugDashServersServerIdIndexRoute
  '/_auth/$slug/_dash/servers/_list/': typeof AuthSlugDashServersListIndexRoute
  '/_auth/$slug/_dash/servers/$serverId/deployments/preview': typeof AuthSlugDashServersServerIdDeploymentsPreviewRoute
  '/_auth/$slug/_dash/servers/$serverId/deployments/production': typeof AuthSlugDashServersServerIdDeploymentsProductionRoute
  '/_auth/$slug/_dash/servers/$serverId/deployments/': typeof AuthSlugDashServersServerIdDeploymentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/$slug'
    | '/github/installed'
    | '/'
    | '/api/auth/$'
    | '/api/github/callback'
    | '/api/github/installs'
    | '/api/github/repos'
    | '/api/sync/v1'
    | '/$slug/deployments'
    | '/$slug/settings'
    | '/api/servers/$serverId/readme'
    | '/$slug/'
    | '/$slug/deployments/$deploymentId'
    | '/$slug/servers/$serverId'
    | '/$slug/servers'
    | '/$slug/deployments/preview'
    | '/$slug/deployments/production'
    | '/$slug/servers/import'
    | '/$slug/servers/new'
    | '/$slug/settings/github'
    | '/$slug/settings/webhooks'
    | '/$slug/deployments/'
    | '/$slug/settings/'
    | '/$slug/servers/$serverId/deployments'
    | '/$slug/deployments/$deploymentId/logs'
    | '/$slug/servers/$serverId/analytics'
    | '/$slug/servers/$serverId/deploy'
    | '/$slug/servers/$serverId/readme'
    | '/$slug/servers/$serverId/settings'
    | '/$slug/servers/private'
    | '/$slug/servers/public'
    | '/$slug/deployments/$deploymentId/'
    | '/$slug/servers/$serverId/'
    | '/$slug/servers/'
    | '/$slug/servers/$serverId/deployments/preview'
    | '/$slug/servers/$serverId/deployments/production'
    | '/$slug/servers/$serverId/deployments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$slug'
    | '/github/installed'
    | '/'
    | '/api/auth/$'
    | '/api/github/callback'
    | '/api/github/installs'
    | '/api/github/repos'
    | '/api/sync/v1'
    | '/api/servers/$serverId/readme'
    | '/$slug/servers'
    | '/$slug/deployments/preview'
    | '/$slug/deployments/production'
    | '/$slug/servers/import'
    | '/$slug/servers/new'
    | '/$slug/settings/github'
    | '/$slug/settings/webhooks'
    | '/$slug/deployments'
    | '/$slug/settings'
    | '/$slug/deployments/$deploymentId/logs'
    | '/$slug/servers/$serverId/analytics'
    | '/$slug/servers/$serverId/deploy'
    | '/$slug/servers/$serverId/readme'
    | '/$slug/servers/$serverId/settings'
    | '/$slug/servers/private'
    | '/$slug/servers/public'
    | '/$slug/deployments/$deploymentId'
    | '/$slug/servers/$serverId'
    | '/$slug/servers/$serverId/deployments/preview'
    | '/$slug/servers/$serverId/deployments/production'
    | '/$slug/servers/$serverId/deployments'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/$slug'
    | '/github/installed'
    | '/_auth/'
    | '/_auth/$slug/_dash'
    | '/api/auth/$'
    | '/api/github/callback'
    | '/api/github/installs'
    | '/api/github/repos'
    | '/api/sync/v1'
    | '/_auth/$slug/_dash/deployments'
    | '/_auth/$slug/_dash/settings'
    | '/api/servers/$serverId/readme'
    | '/_auth/$slug/_dash/'
    | '/_auth/$slug/_dash/deployments/$deploymentId'
    | '/_auth/$slug/_dash/servers/$serverId'
    | '/_auth/$slug/_dash/servers'
    | '/_auth/$slug/_dash/servers/_list'
    | '/_auth/$slug/_dash/deployments/preview'
    | '/_auth/$slug/_dash/deployments/production'
    | '/_auth/$slug/_dash/servers/import'
    | '/_auth/$slug/_dash/servers/new'
    | '/_auth/$slug/_dash/settings/github'
    | '/_auth/$slug/_dash/settings/webhooks'
    | '/_auth/$slug/_dash/deployments/'
    | '/_auth/$slug/_dash/settings/'
    | '/_auth/$slug/_dash/servers/$serverId/deployments'
    | '/_auth/$slug/_dash/deployments/$deploymentId/logs'
    | '/_auth/$slug/_dash/servers/$serverId/analytics'
    | '/_auth/$slug/_dash/servers/$serverId/deploy'
    | '/_auth/$slug/_dash/servers/$serverId/readme'
    | '/_auth/$slug/_dash/servers/$serverId/settings'
    | '/_auth/$slug/_dash/servers/_list/private'
    | '/_auth/$slug/_dash/servers/_list/public'
    | '/_auth/$slug/_dash/deployments/$deploymentId/'
    | '/_auth/$slug/_dash/servers/$serverId/'
    | '/_auth/$slug/_dash/servers/_list/'
    | '/_auth/$slug/_dash/servers/$serverId/deployments/preview'
    | '/_auth/$slug/_dash/servers/$serverId/deployments/production'
    | '/_auth/$slug/_dash/servers/$serverId/deployments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  GithubInstalledRoute: typeof GithubInstalledRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGithubCallbackRoute: typeof ApiGithubCallbackRoute
  ApiGithubInstallsRoute: typeof ApiGithubInstallsRoute
  ApiGithubReposRoute: typeof ApiGithubReposRoute
  ApiSyncV1Route: typeof ApiSyncV1Route
  ApiServersServerIdReadmeRoute: typeof ApiServersServerIdReadmeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/github/installed': {
      id: '/github/installed'
      path: '/github/installed'
      fullPath: '/github/installed'
      preLoaderRoute: typeof GithubInstalledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/$slug': {
      id: '/_auth/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof AuthSlugRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/sync/v1': {
      id: '/api/sync/v1'
      path: '/api/sync/v1'
      fullPath: '/api/sync/v1'
      preLoaderRoute: typeof ApiSyncV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/repos': {
      id: '/api/github/repos'
      path: '/api/github/repos'
      fullPath: '/api/github/repos'
      preLoaderRoute: typeof ApiGithubReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/installs': {
      id: '/api/github/installs'
      path: '/api/github/installs'
      fullPath: '/api/github/installs'
      preLoaderRoute: typeof ApiGithubInstallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/callback': {
      id: '/api/github/callback'
      path: '/api/github/callback'
      fullPath: '/api/github/callback'
      preLoaderRoute: typeof ApiGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/$slug/_dash': {
      id: '/_auth/$slug/_dash'
      path: ''
      fullPath: '/$slug'
      preLoaderRoute: typeof AuthSlugDashRouteRouteImport
      parentRoute: typeof AuthSlugRouteRoute
    }
    '/_auth/$slug/_dash/servers': {
      id: '/_auth/$slug/_dash/servers'
      path: '/servers'
      fullPath: '/$slug/servers'
      preLoaderRoute: typeof AuthSlugDashServersRouteImport
      parentRoute: typeof AuthSlugDashRouteRoute
    }
    '/_auth/$slug/_dash/': {
      id: '/_auth/$slug/_dash/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof AuthSlugDashIndexRouteImport
      parentRoute: typeof AuthSlugDashRouteRoute
    }
    '/api/servers/$serverId/readme': {
      id: '/api/servers/$serverId/readme'
      path: '/api/servers/$serverId/readme'
      fullPath: '/api/servers/$serverId/readme'
      preLoaderRoute: typeof ApiServersServerIdReadmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/$slug/_dash/settings': {
      id: '/_auth/$slug/_dash/settings'
      path: '/settings'
      fullPath: '/$slug/settings'
      preLoaderRoute: typeof AuthSlugDashSettingsRouteRouteImport
      parentRoute: typeof AuthSlugDashRouteRoute
    }
    '/_auth/$slug/_dash/deployments': {
      id: '/_auth/$slug/_dash/deployments'
      path: '/deployments'
      fullPath: '/$slug/deployments'
      preLoaderRoute: typeof AuthSlugDashDeploymentsRouteRouteImport
      parentRoute: typeof AuthSlugDashRouteRoute
    }
    '/_auth/$slug/_dash/settings/': {
      id: '/_auth/$slug/_dash/settings/'
      path: '/'
      fullPath: '/$slug/settings/'
      preLoaderRoute: typeof AuthSlugDashSettingsIndexRouteImport
      parentRoute: typeof AuthSlugDashSettingsRouteRoute
    }
    '/_auth/$slug/_dash/deployments/': {
      id: '/_auth/$slug/_dash/deployments/'
      path: '/'
      fullPath: '/$slug/deployments/'
      preLoaderRoute: typeof AuthSlugDashDeploymentsIndexRouteImport
      parentRoute: typeof AuthSlugDashDeploymentsRouteRoute
    }
    '/_auth/$slug/_dash/settings/webhooks': {
      id: '/_auth/$slug/_dash/settings/webhooks'
      path: '/webhooks'
      fullPath: '/$slug/settings/webhooks'
      preLoaderRoute: typeof AuthSlugDashSettingsWebhooksRouteImport
      parentRoute: typeof AuthSlugDashSettingsRouteRoute
    }
    '/_auth/$slug/_dash/settings/github': {
      id: '/_auth/$slug/_dash/settings/github'
      path: '/github'
      fullPath: '/$slug/settings/github'
      preLoaderRoute: typeof AuthSlugDashSettingsGithubRouteImport
      parentRoute: typeof AuthSlugDashSettingsRouteRoute
    }
    '/_auth/$slug/_dash/servers/new': {
      id: '/_auth/$slug/_dash/servers/new'
      path: '/new'
      fullPath: '/$slug/servers/new'
      preLoaderRoute: typeof AuthSlugDashServersNewRouteImport
      parentRoute: typeof AuthSlugDashServersRoute
    }
    '/_auth/$slug/_dash/servers/import': {
      id: '/_auth/$slug/_dash/servers/import'
      path: '/import'
      fullPath: '/$slug/servers/import'
      preLoaderRoute: typeof AuthSlugDashServersImportRouteImport
      parentRoute: typeof AuthSlugDashServersRoute
    }
    '/_auth/$slug/_dash/deployments/production': {
      id: '/_auth/$slug/_dash/deployments/production'
      path: '/production'
      fullPath: '/$slug/deployments/production'
      preLoaderRoute: typeof AuthSlugDashDeploymentsProductionRouteImport
      parentRoute: typeof AuthSlugDashDeploymentsRouteRoute
    }
    '/_auth/$slug/_dash/deployments/preview': {
      id: '/_auth/$slug/_dash/deployments/preview'
      path: '/preview'
      fullPath: '/$slug/deployments/preview'
      preLoaderRoute: typeof AuthSlugDashDeploymentsPreviewRouteImport
      parentRoute: typeof AuthSlugDashDeploymentsRouteRoute
    }
    '/_auth/$slug/_dash/servers/_list': {
      id: '/_auth/$slug/_dash/servers/_list'
      path: '/servers'
      fullPath: '/$slug/servers'
      preLoaderRoute: typeof AuthSlugDashServersListRouteRouteImport
      parentRoute: typeof AuthSlugDashServersRoute
    }
    '/_auth/$slug/_dash/servers/$serverId': {
      id: '/_auth/$slug/_dash/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/$slug/servers/$serverId'
      preLoaderRoute: typeof AuthSlugDashServersServerIdRouteRouteImport
      parentRoute: typeof AuthSlugDashRouteRoute
    }
    '/_auth/$slug/_dash/deployments/$deploymentId': {
      id: '/_auth/$slug/_dash/deployments/$deploymentId'
      path: '/$deploymentId'
      fullPath: '/$slug/deployments/$deploymentId'
      preLoaderRoute: typeof AuthSlugDashDeploymentsDeploymentIdRouteRouteImport
      parentRoute: typeof AuthSlugDashDeploymentsRouteRoute
    }
    '/_auth/$slug/_dash/servers/_list/': {
      id: '/_auth/$slug/_dash/servers/_list/'
      path: '/'
      fullPath: '/$slug/servers/'
      preLoaderRoute: typeof AuthSlugDashServersListIndexRouteImport
      parentRoute: typeof AuthSlugDashServersListRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/': {
      id: '/_auth/$slug/_dash/servers/$serverId/'
      path: '/'
      fullPath: '/$slug/servers/$serverId/'
      preLoaderRoute: typeof AuthSlugDashServersServerIdIndexRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdRouteRoute
    }
    '/_auth/$slug/_dash/deployments/$deploymentId/': {
      id: '/_auth/$slug/_dash/deployments/$deploymentId/'
      path: '/'
      fullPath: '/$slug/deployments/$deploymentId/'
      preLoaderRoute: typeof AuthSlugDashDeploymentsDeploymentIdIndexRouteImport
      parentRoute: typeof AuthSlugDashDeploymentsDeploymentIdRouteRoute
    }
    '/_auth/$slug/_dash/servers/_list/public': {
      id: '/_auth/$slug/_dash/servers/_list/public'
      path: '/public'
      fullPath: '/$slug/servers/public'
      preLoaderRoute: typeof AuthSlugDashServersListPublicRouteImport
      parentRoute: typeof AuthSlugDashServersListRouteRoute
    }
    '/_auth/$slug/_dash/servers/_list/private': {
      id: '/_auth/$slug/_dash/servers/_list/private'
      path: '/private'
      fullPath: '/$slug/servers/private'
      preLoaderRoute: typeof AuthSlugDashServersListPrivateRouteImport
      parentRoute: typeof AuthSlugDashServersListRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/settings': {
      id: '/_auth/$slug/_dash/servers/$serverId/settings'
      path: '/settings'
      fullPath: '/$slug/servers/$serverId/settings'
      preLoaderRoute: typeof AuthSlugDashServersServerIdSettingsRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/readme': {
      id: '/_auth/$slug/_dash/servers/$serverId/readme'
      path: '/readme'
      fullPath: '/$slug/servers/$serverId/readme'
      preLoaderRoute: typeof AuthSlugDashServersServerIdReadmeRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/deploy': {
      id: '/_auth/$slug/_dash/servers/$serverId/deploy'
      path: '/deploy'
      fullPath: '/$slug/servers/$serverId/deploy'
      preLoaderRoute: typeof AuthSlugDashServersServerIdDeployRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/analytics': {
      id: '/_auth/$slug/_dash/servers/$serverId/analytics'
      path: '/analytics'
      fullPath: '/$slug/servers/$serverId/analytics'
      preLoaderRoute: typeof AuthSlugDashServersServerIdAnalyticsRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdRouteRoute
    }
    '/_auth/$slug/_dash/deployments/$deploymentId/logs': {
      id: '/_auth/$slug/_dash/deployments/$deploymentId/logs'
      path: '/logs'
      fullPath: '/$slug/deployments/$deploymentId/logs'
      preLoaderRoute: typeof AuthSlugDashDeploymentsDeploymentIdLogsRouteImport
      parentRoute: typeof AuthSlugDashDeploymentsDeploymentIdRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/deployments': {
      id: '/_auth/$slug/_dash/servers/$serverId/deployments'
      path: '/deployments'
      fullPath: '/$slug/servers/$serverId/deployments'
      preLoaderRoute: typeof AuthSlugDashServersServerIdDeploymentsRouteRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/deployments/': {
      id: '/_auth/$slug/_dash/servers/$serverId/deployments/'
      path: '/'
      fullPath: '/$slug/servers/$serverId/deployments/'
      preLoaderRoute: typeof AuthSlugDashServersServerIdDeploymentsIndexRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdDeploymentsRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/deployments/production': {
      id: '/_auth/$slug/_dash/servers/$serverId/deployments/production'
      path: '/production'
      fullPath: '/$slug/servers/$serverId/deployments/production'
      preLoaderRoute: typeof AuthSlugDashServersServerIdDeploymentsProductionRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdDeploymentsRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/deployments/preview': {
      id: '/_auth/$slug/_dash/servers/$serverId/deployments/preview'
      path: '/preview'
      fullPath: '/$slug/servers/$serverId/deployments/preview'
      preLoaderRoute: typeof AuthSlugDashServersServerIdDeploymentsPreviewRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdDeploymentsRouteRoute
    }
  }
}

interface AuthSlugDashDeploymentsDeploymentIdRouteRouteChildren {
  AuthSlugDashDeploymentsDeploymentIdLogsRoute: typeof AuthSlugDashDeploymentsDeploymentIdLogsRoute
  AuthSlugDashDeploymentsDeploymentIdIndexRoute: typeof AuthSlugDashDeploymentsDeploymentIdIndexRoute
}

const AuthSlugDashDeploymentsDeploymentIdRouteRouteChildren: AuthSlugDashDeploymentsDeploymentIdRouteRouteChildren =
  {
    AuthSlugDashDeploymentsDeploymentIdLogsRoute:
      AuthSlugDashDeploymentsDeploymentIdLogsRoute,
    AuthSlugDashDeploymentsDeploymentIdIndexRoute:
      AuthSlugDashDeploymentsDeploymentIdIndexRoute,
  }

const AuthSlugDashDeploymentsDeploymentIdRouteRouteWithChildren =
  AuthSlugDashDeploymentsDeploymentIdRouteRoute._addFileChildren(
    AuthSlugDashDeploymentsDeploymentIdRouteRouteChildren,
  )

interface AuthSlugDashDeploymentsRouteRouteChildren {
  AuthSlugDashDeploymentsDeploymentIdRouteRoute: typeof AuthSlugDashDeploymentsDeploymentIdRouteRouteWithChildren
  AuthSlugDashDeploymentsPreviewRoute: typeof AuthSlugDashDeploymentsPreviewRoute
  AuthSlugDashDeploymentsProductionRoute: typeof AuthSlugDashDeploymentsProductionRoute
  AuthSlugDashDeploymentsIndexRoute: typeof AuthSlugDashDeploymentsIndexRoute
}

const AuthSlugDashDeploymentsRouteRouteChildren: AuthSlugDashDeploymentsRouteRouteChildren =
  {
    AuthSlugDashDeploymentsDeploymentIdRouteRoute:
      AuthSlugDashDeploymentsDeploymentIdRouteRouteWithChildren,
    AuthSlugDashDeploymentsPreviewRoute: AuthSlugDashDeploymentsPreviewRoute,
    AuthSlugDashDeploymentsProductionRoute:
      AuthSlugDashDeploymentsProductionRoute,
    AuthSlugDashDeploymentsIndexRoute: AuthSlugDashDeploymentsIndexRoute,
  }

const AuthSlugDashDeploymentsRouteRouteWithChildren =
  AuthSlugDashDeploymentsRouteRoute._addFileChildren(
    AuthSlugDashDeploymentsRouteRouteChildren,
  )

interface AuthSlugDashSettingsRouteRouteChildren {
  AuthSlugDashSettingsGithubRoute: typeof AuthSlugDashSettingsGithubRoute
  AuthSlugDashSettingsWebhooksRoute: typeof AuthSlugDashSettingsWebhooksRoute
  AuthSlugDashSettingsIndexRoute: typeof AuthSlugDashSettingsIndexRoute
}

const AuthSlugDashSettingsRouteRouteChildren: AuthSlugDashSettingsRouteRouteChildren =
  {
    AuthSlugDashSettingsGithubRoute: AuthSlugDashSettingsGithubRoute,
    AuthSlugDashSettingsWebhooksRoute: AuthSlugDashSettingsWebhooksRoute,
    AuthSlugDashSettingsIndexRoute: AuthSlugDashSettingsIndexRoute,
  }

const AuthSlugDashSettingsRouteRouteWithChildren =
  AuthSlugDashSettingsRouteRoute._addFileChildren(
    AuthSlugDashSettingsRouteRouteChildren,
  )

interface AuthSlugDashServersServerIdDeploymentsRouteRouteChildren {
  AuthSlugDashServersServerIdDeploymentsPreviewRoute: typeof AuthSlugDashServersServerIdDeploymentsPreviewRoute
  AuthSlugDashServersServerIdDeploymentsProductionRoute: typeof AuthSlugDashServersServerIdDeploymentsProductionRoute
  AuthSlugDashServersServerIdDeploymentsIndexRoute: typeof AuthSlugDashServersServerIdDeploymentsIndexRoute
}

const AuthSlugDashServersServerIdDeploymentsRouteRouteChildren: AuthSlugDashServersServerIdDeploymentsRouteRouteChildren =
  {
    AuthSlugDashServersServerIdDeploymentsPreviewRoute:
      AuthSlugDashServersServerIdDeploymentsPreviewRoute,
    AuthSlugDashServersServerIdDeploymentsProductionRoute:
      AuthSlugDashServersServerIdDeploymentsProductionRoute,
    AuthSlugDashServersServerIdDeploymentsIndexRoute:
      AuthSlugDashServersServerIdDeploymentsIndexRoute,
  }

const AuthSlugDashServersServerIdDeploymentsRouteRouteWithChildren =
  AuthSlugDashServersServerIdDeploymentsRouteRoute._addFileChildren(
    AuthSlugDashServersServerIdDeploymentsRouteRouteChildren,
  )

interface AuthSlugDashServersServerIdRouteRouteChildren {
  AuthSlugDashServersServerIdDeploymentsRouteRoute: typeof AuthSlugDashServersServerIdDeploymentsRouteRouteWithChildren
  AuthSlugDashServersServerIdAnalyticsRoute: typeof AuthSlugDashServersServerIdAnalyticsRoute
  AuthSlugDashServersServerIdDeployRoute: typeof AuthSlugDashServersServerIdDeployRoute
  AuthSlugDashServersServerIdReadmeRoute: typeof AuthSlugDashServersServerIdReadmeRoute
  AuthSlugDashServersServerIdSettingsRoute: typeof AuthSlugDashServersServerIdSettingsRoute
  AuthSlugDashServersServerIdIndexRoute: typeof AuthSlugDashServersServerIdIndexRoute
}

const AuthSlugDashServersServerIdRouteRouteChildren: AuthSlugDashServersServerIdRouteRouteChildren =
  {
    AuthSlugDashServersServerIdDeploymentsRouteRoute:
      AuthSlugDashServersServerIdDeploymentsRouteRouteWithChildren,
    AuthSlugDashServersServerIdAnalyticsRoute:
      AuthSlugDashServersServerIdAnalyticsRoute,
    AuthSlugDashServersServerIdDeployRoute:
      AuthSlugDashServersServerIdDeployRoute,
    AuthSlugDashServersServerIdReadmeRoute:
      AuthSlugDashServersServerIdReadmeRoute,
    AuthSlugDashServersServerIdSettingsRoute:
      AuthSlugDashServersServerIdSettingsRoute,
    AuthSlugDashServersServerIdIndexRoute:
      AuthSlugDashServersServerIdIndexRoute,
  }

const AuthSlugDashServersServerIdRouteRouteWithChildren =
  AuthSlugDashServersServerIdRouteRoute._addFileChildren(
    AuthSlugDashServersServerIdRouteRouteChildren,
  )

interface AuthSlugDashServersListRouteRouteChildren {
  AuthSlugDashServersListPrivateRoute: typeof AuthSlugDashServersListPrivateRoute
  AuthSlugDashServersListPublicRoute: typeof AuthSlugDashServersListPublicRoute
  AuthSlugDashServersListIndexRoute: typeof AuthSlugDashServersListIndexRoute
}

const AuthSlugDashServersListRouteRouteChildren: AuthSlugDashServersListRouteRouteChildren =
  {
    AuthSlugDashServersListPrivateRoute: AuthSlugDashServersListPrivateRoute,
    AuthSlugDashServersListPublicRoute: AuthSlugDashServersListPublicRoute,
    AuthSlugDashServersListIndexRoute: AuthSlugDashServersListIndexRoute,
  }

const AuthSlugDashServersListRouteRouteWithChildren =
  AuthSlugDashServersListRouteRoute._addFileChildren(
    AuthSlugDashServersListRouteRouteChildren,
  )

interface AuthSlugDashServersRouteChildren {
  AuthSlugDashServersListRouteRoute: typeof AuthSlugDashServersListRouteRouteWithChildren
  AuthSlugDashServersImportRoute: typeof AuthSlugDashServersImportRoute
  AuthSlugDashServersNewRoute: typeof AuthSlugDashServersNewRoute
}

const AuthSlugDashServersRouteChildren: AuthSlugDashServersRouteChildren = {
  AuthSlugDashServersListRouteRoute:
    AuthSlugDashServersListRouteRouteWithChildren,
  AuthSlugDashServersImportRoute: AuthSlugDashServersImportRoute,
  AuthSlugDashServersNewRoute: AuthSlugDashServersNewRoute,
}

const AuthSlugDashServersRouteWithChildren =
  AuthSlugDashServersRoute._addFileChildren(AuthSlugDashServersRouteChildren)

interface AuthSlugDashRouteRouteChildren {
  AuthSlugDashDeploymentsRouteRoute: typeof AuthSlugDashDeploymentsRouteRouteWithChildren
  AuthSlugDashSettingsRouteRoute: typeof AuthSlugDashSettingsRouteRouteWithChildren
  AuthSlugDashIndexRoute: typeof AuthSlugDashIndexRoute
  AuthSlugDashServersServerIdRouteRoute: typeof AuthSlugDashServersServerIdRouteRouteWithChildren
  AuthSlugDashServersRoute: typeof AuthSlugDashServersRouteWithChildren
}

const AuthSlugDashRouteRouteChildren: AuthSlugDashRouteRouteChildren = {
  AuthSlugDashDeploymentsRouteRoute:
    AuthSlugDashDeploymentsRouteRouteWithChildren,
  AuthSlugDashSettingsRouteRoute: AuthSlugDashSettingsRouteRouteWithChildren,
  AuthSlugDashIndexRoute: AuthSlugDashIndexRoute,
  AuthSlugDashServersServerIdRouteRoute:
    AuthSlugDashServersServerIdRouteRouteWithChildren,
  AuthSlugDashServersRoute: AuthSlugDashServersRouteWithChildren,
}

const AuthSlugDashRouteRouteWithChildren =
  AuthSlugDashRouteRoute._addFileChildren(AuthSlugDashRouteRouteChildren)

interface AuthSlugRouteRouteChildren {
  AuthSlugDashRouteRoute: typeof AuthSlugDashRouteRouteWithChildren
}

const AuthSlugRouteRouteChildren: AuthSlugRouteRouteChildren = {
  AuthSlugDashRouteRoute: AuthSlugDashRouteRouteWithChildren,
}

const AuthSlugRouteRouteWithChildren = AuthSlugRouteRoute._addFileChildren(
  AuthSlugRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSlugRouteRoute: typeof AuthSlugRouteRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSlugRouteRoute: AuthSlugRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  GithubInstalledRoute: GithubInstalledRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGithubCallbackRoute: ApiGithubCallbackRoute,
  ApiGithubInstallsRoute: ApiGithubInstallsRoute,
  ApiGithubReposRoute: ApiGithubReposRoute,
  ApiSyncV1Route: ApiSyncV1Route,
  ApiServersServerIdReadmeRoute: ApiServersServerIdReadmeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
