/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as GithubInstalledRouteImport } from './routes/github/installed'
import { Route as AuthSlugRouteRouteImport } from './routes/_auth/$slug/route'
import { Route as ApiSyncV1RouteImport } from './routes/api/sync/v1'
import { Route as ApiGithubReposRouteImport } from './routes/api/github.repos'
import { Route as ApiGithubInstallsRouteImport } from './routes/api/github.installs'
import { Route as ApiGithubCallbackRouteImport } from './routes/api/github.callback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthUsersUsernameRouteImport } from './routes/_auth/users.$username'
import { Route as AuthSlugDashRouteRouteImport } from './routes/_auth/$slug/_dash/route'
import { Route as AuthSlugDashIndexRouteImport } from './routes/_auth/$slug/_dash/index'
import { Route as ApiServersServerIdReadmeRouteImport } from './routes/api/servers/$serverId.readme'
import { Route as AuthSlugDashDeploymentsRouteImport } from './routes/_auth/$slug/_dash/deployments'
import { Route as AuthSlugDeploymentsDeploymentIdRouteRouteImport } from './routes/_auth/$slug/deployments.$deploymentId/route'
import { Route as AuthSlugDashSettingsRouteRouteImport } from './routes/_auth/$slug/_dash/settings/route'
import { Route as AuthSlugDeploymentsDeploymentIdIndexRouteImport } from './routes/_auth/$slug/deployments.$deploymentId/index'
import { Route as AuthSlugDashSettingsIndexRouteImport } from './routes/_auth/$slug/_dash/settings/index'
import { Route as AuthSlugDashDeploymentsIndexRouteImport } from './routes/_auth/$slug/_dash/deployments.index'
import { Route as AuthSlugDeploymentsDeploymentIdLogsRouteImport } from './routes/_auth/$slug/deployments.$deploymentId/logs'
import { Route as AuthSlugDashSettingsWebhooksRouteImport } from './routes/_auth/$slug/_dash/settings/webhooks'
import { Route as AuthSlugDashSettingsGithubRouteImport } from './routes/_auth/$slug/_dash/settings/github'
import { Route as AuthSlugDashServersNewRouteImport } from './routes/_auth/$slug/_dash/servers/new'
import { Route as AuthSlugDashServersImportRouteImport } from './routes/_auth/$slug/_dash/servers/import'
import { Route as AuthSlugDashDeploymentsProductionRouteImport } from './routes/_auth/$slug/_dash/deployments.production'
import { Route as AuthSlugDashDeploymentsPreviewRouteImport } from './routes/_auth/$slug/_dash/deployments.preview'
import { Route as AuthSlugDashServersListRouteRouteImport } from './routes/_auth/$slug/_dash/servers/_list/route'
import { Route as AuthSlugDashServersListIndexRouteImport } from './routes/_auth/$slug/_dash/servers/_list/index'
import { Route as AuthSlugDashServersListPublicRouteImport } from './routes/_auth/$slug/_dash/servers/_list/public'
import { Route as AuthSlugDashServersListPrivateRouteImport } from './routes/_auth/$slug/_dash/servers/_list/private'
import { Route as AuthSlugDashServersServerIdDeployRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/deploy'
import { Route as AuthSlugDashServersServerIdServerRouteRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/_server/route'
import { Route as AuthSlugDashServersServerIdServerIndexRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/_server/index'
import { Route as AuthSlugDashServersServerIdServerSettingsRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/_server/settings'
import { Route as AuthSlugDashServersServerIdServerReadmeRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/_server/readme'
import { Route as AuthSlugDashServersServerIdServerDeploymentsRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/_server/deployments'
import { Route as AuthSlugDashServersServerIdServerAnalyticsRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/_server/analytics'
import { Route as AuthSlugDashServersServerIdServerDeploymentsIndexRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/_server/deployments.index'
import { Route as AuthSlugDashServersServerIdServerDeploymentsProductionRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/_server/deployments.production'
import { Route as AuthSlugDashServersServerIdServerDeploymentsPreviewRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/_server/deployments.preview'

const AuthSlugDashServersRouteImport = createFileRoute(
  '/_auth/$slug/_dash/servers',
)()
const AuthSlugDashServersServerIdRouteImport = createFileRoute(
  '/_auth/$slug/_dash/servers/$serverId',
)()

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const GithubInstalledRoute = GithubInstalledRouteImport.update({
  id: '/github/installed',
  path: '/github/installed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSlugRouteRoute = AuthSlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiSyncV1Route = ApiSyncV1RouteImport.update({
  id: '/api/sync/v1',
  path: '/api/sync/v1',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubReposRoute = ApiGithubReposRouteImport.update({
  id: '/api/github/repos',
  path: '/api/github/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubInstallsRoute = ApiGithubInstallsRouteImport.update({
  id: '/api/github/installs',
  path: '/api/github/installs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCallbackRoute = ApiGithubCallbackRouteImport.update({
  id: '/api/github/callback',
  path: '/api/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUsersUsernameRoute = AuthUsersUsernameRouteImport.update({
  id: '/users/$username',
  path: '/users/$username',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSlugDashRouteRoute = AuthSlugDashRouteRouteImport.update({
  id: '/_dash',
  getParentRoute: () => AuthSlugRouteRoute,
} as any)
const AuthSlugDashServersRoute = AuthSlugDashServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AuthSlugDashRouteRoute,
} as any)
const AuthSlugDashIndexRoute = AuthSlugDashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSlugDashRouteRoute,
} as any)
const ApiServersServerIdReadmeRoute =
  ApiServersServerIdReadmeRouteImport.update({
    id: '/api/servers/$serverId/readme',
    path: '/api/servers/$serverId/readme',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSlugDashDeploymentsRoute = AuthSlugDashDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => AuthSlugDashRouteRoute,
} as any)
const AuthSlugDeploymentsDeploymentIdRouteRoute =
  AuthSlugDeploymentsDeploymentIdRouteRouteImport.update({
    id: '/deployments/$deploymentId',
    path: '/deployments/$deploymentId',
    getParentRoute: () => AuthSlugRouteRoute,
  } as any)
const AuthSlugDashSettingsRouteRoute =
  AuthSlugDashSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthSlugDashRouteRoute,
  } as any)
const AuthSlugDashServersServerIdRoute =
  AuthSlugDashServersServerIdRouteImport.update({
    id: '/$serverId',
    path: '/$serverId',
    getParentRoute: () => AuthSlugDashServersRoute,
  } as any)
const AuthSlugDeploymentsDeploymentIdIndexRoute =
  AuthSlugDeploymentsDeploymentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthSlugDeploymentsDeploymentIdRouteRoute,
  } as any)
const AuthSlugDashSettingsIndexRoute =
  AuthSlugDashSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthSlugDashSettingsRouteRoute,
  } as any)
const AuthSlugDashDeploymentsIndexRoute =
  AuthSlugDashDeploymentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthSlugDashDeploymentsRoute,
  } as any)
const AuthSlugDeploymentsDeploymentIdLogsRoute =
  AuthSlugDeploymentsDeploymentIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthSlugDeploymentsDeploymentIdRouteRoute,
  } as any)
const AuthSlugDashSettingsWebhooksRoute =
  AuthSlugDashSettingsWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthSlugDashSettingsRouteRoute,
  } as any)
const AuthSlugDashSettingsGithubRoute =
  AuthSlugDashSettingsGithubRouteImport.update({
    id: '/github',
    path: '/github',
    getParentRoute: () => AuthSlugDashSettingsRouteRoute,
  } as any)
const AuthSlugDashServersNewRoute = AuthSlugDashServersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthSlugDashServersRoute,
} as any)
const AuthSlugDashServersImportRoute =
  AuthSlugDashServersImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthSlugDashServersRoute,
  } as any)
const AuthSlugDashDeploymentsProductionRoute =
  AuthSlugDashDeploymentsProductionRouteImport.update({
    id: '/production',
    path: '/production',
    getParentRoute: () => AuthSlugDashDeploymentsRoute,
  } as any)
const AuthSlugDashDeploymentsPreviewRoute =
  AuthSlugDashDeploymentsPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AuthSlugDashDeploymentsRoute,
  } as any)
const AuthSlugDashServersListRouteRoute =
  AuthSlugDashServersListRouteRouteImport.update({
    id: '/_list',
    getParentRoute: () => AuthSlugDashServersRoute,
  } as any)
const AuthSlugDashServersListIndexRoute =
  AuthSlugDashServersListIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthSlugDashServersListRouteRoute,
  } as any)
const AuthSlugDashServersListPublicRoute =
  AuthSlugDashServersListPublicRouteImport.update({
    id: '/public',
    path: '/public',
    getParentRoute: () => AuthSlugDashServersListRouteRoute,
  } as any)
const AuthSlugDashServersListPrivateRoute =
  AuthSlugDashServersListPrivateRouteImport.update({
    id: '/private',
    path: '/private',
    getParentRoute: () => AuthSlugDashServersListRouteRoute,
  } as any)
const AuthSlugDashServersServerIdDeployRoute =
  AuthSlugDashServersServerIdDeployRouteImport.update({
    id: '/deploy',
    path: '/deploy',
    getParentRoute: () => AuthSlugDashServersServerIdRoute,
  } as any)
const AuthSlugDashServersServerIdServerRouteRoute =
  AuthSlugDashServersServerIdServerRouteRouteImport.update({
    id: '/_server',
    getParentRoute: () => AuthSlugDashServersServerIdRoute,
  } as any)
const AuthSlugDashServersServerIdServerIndexRoute =
  AuthSlugDashServersServerIdServerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthSlugDashServersServerIdServerRouteRoute,
  } as any)
const AuthSlugDashServersServerIdServerSettingsRoute =
  AuthSlugDashServersServerIdServerSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthSlugDashServersServerIdServerRouteRoute,
  } as any)
const AuthSlugDashServersServerIdServerReadmeRoute =
  AuthSlugDashServersServerIdServerReadmeRouteImport.update({
    id: '/readme',
    path: '/readme',
    getParentRoute: () => AuthSlugDashServersServerIdServerRouteRoute,
  } as any)
const AuthSlugDashServersServerIdServerDeploymentsRoute =
  AuthSlugDashServersServerIdServerDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AuthSlugDashServersServerIdServerRouteRoute,
  } as any)
const AuthSlugDashServersServerIdServerAnalyticsRoute =
  AuthSlugDashServersServerIdServerAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthSlugDashServersServerIdServerRouteRoute,
  } as any)
const AuthSlugDashServersServerIdServerDeploymentsIndexRoute =
  AuthSlugDashServersServerIdServerDeploymentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthSlugDashServersServerIdServerDeploymentsRoute,
  } as any)
const AuthSlugDashServersServerIdServerDeploymentsProductionRoute =
  AuthSlugDashServersServerIdServerDeploymentsProductionRouteImport.update({
    id: '/production',
    path: '/production',
    getParentRoute: () => AuthSlugDashServersServerIdServerDeploymentsRoute,
  } as any)
const AuthSlugDashServersServerIdServerDeploymentsPreviewRoute =
  AuthSlugDashServersServerIdServerDeploymentsPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AuthSlugDashServersServerIdServerDeploymentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/$slug': typeof AuthSlugDashRouteRouteWithChildren
  '/github/installed': typeof GithubInstalledRoute
  '/': typeof AuthIndexRoute
  '/users/$username': typeof AuthUsersUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/installs': typeof ApiGithubInstallsRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/sync/v1': typeof ApiSyncV1Route
  '/$slug/settings': typeof AuthSlugDashSettingsRouteRouteWithChildren
  '/$slug/deployments/$deploymentId': typeof AuthSlugDeploymentsDeploymentIdRouteRouteWithChildren
  '/$slug/deployments': typeof AuthSlugDashDeploymentsRouteWithChildren
  '/api/servers/$serverId/readme': typeof ApiServersServerIdReadmeRoute
  '/$slug/': typeof AuthSlugDashIndexRoute
  '/$slug/servers': typeof AuthSlugDashServersListRouteRouteWithChildren
  '/$slug/deployments/preview': typeof AuthSlugDashDeploymentsPreviewRoute
  '/$slug/deployments/production': typeof AuthSlugDashDeploymentsProductionRoute
  '/$slug/servers/import': typeof AuthSlugDashServersImportRoute
  '/$slug/servers/new': typeof AuthSlugDashServersNewRoute
  '/$slug/settings/github': typeof AuthSlugDashSettingsGithubRoute
  '/$slug/settings/webhooks': typeof AuthSlugDashSettingsWebhooksRoute
  '/$slug/deployments/$deploymentId/logs': typeof AuthSlugDeploymentsDeploymentIdLogsRoute
  '/$slug/deployments/': typeof AuthSlugDashDeploymentsIndexRoute
  '/$slug/settings/': typeof AuthSlugDashSettingsIndexRoute
  '/$slug/deployments/$deploymentId/': typeof AuthSlugDeploymentsDeploymentIdIndexRoute
  '/$slug/servers/$serverId': typeof AuthSlugDashServersServerIdServerRouteRouteWithChildren
  '/$slug/servers/$serverId/deploy': typeof AuthSlugDashServersServerIdDeployRoute
  '/$slug/servers/private': typeof AuthSlugDashServersListPrivateRoute
  '/$slug/servers/public': typeof AuthSlugDashServersListPublicRoute
  '/$slug/servers/': typeof AuthSlugDashServersListIndexRoute
  '/$slug/servers/$serverId/analytics': typeof AuthSlugDashServersServerIdServerAnalyticsRoute
  '/$slug/servers/$serverId/deployments': typeof AuthSlugDashServersServerIdServerDeploymentsRouteWithChildren
  '/$slug/servers/$serverId/readme': typeof AuthSlugDashServersServerIdServerReadmeRoute
  '/$slug/servers/$serverId/settings': typeof AuthSlugDashServersServerIdServerSettingsRoute
  '/$slug/servers/$serverId/': typeof AuthSlugDashServersServerIdServerIndexRoute
  '/$slug/servers/$serverId/deployments/preview': typeof AuthSlugDashServersServerIdServerDeploymentsPreviewRoute
  '/$slug/servers/$serverId/deployments/production': typeof AuthSlugDashServersServerIdServerDeploymentsProductionRoute
  '/$slug/servers/$serverId/deployments/': typeof AuthSlugDashServersServerIdServerDeploymentsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$slug': typeof AuthSlugDashIndexRoute
  '/github/installed': typeof GithubInstalledRoute
  '/': typeof AuthIndexRoute
  '/users/$username': typeof AuthUsersUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/installs': typeof ApiGithubInstallsRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/sync/v1': typeof ApiSyncV1Route
  '/api/servers/$serverId/readme': typeof ApiServersServerIdReadmeRoute
  '/$slug/servers': typeof AuthSlugDashServersListIndexRoute
  '/$slug/deployments/preview': typeof AuthSlugDashDeploymentsPreviewRoute
  '/$slug/deployments/production': typeof AuthSlugDashDeploymentsProductionRoute
  '/$slug/servers/import': typeof AuthSlugDashServersImportRoute
  '/$slug/servers/new': typeof AuthSlugDashServersNewRoute
  '/$slug/settings/github': typeof AuthSlugDashSettingsGithubRoute
  '/$slug/settings/webhooks': typeof AuthSlugDashSettingsWebhooksRoute
  '/$slug/deployments/$deploymentId/logs': typeof AuthSlugDeploymentsDeploymentIdLogsRoute
  '/$slug/deployments': typeof AuthSlugDashDeploymentsIndexRoute
  '/$slug/settings': typeof AuthSlugDashSettingsIndexRoute
  '/$slug/deployments/$deploymentId': typeof AuthSlugDeploymentsDeploymentIdIndexRoute
  '/$slug/servers/$serverId': typeof AuthSlugDashServersServerIdServerIndexRoute
  '/$slug/servers/$serverId/deploy': typeof AuthSlugDashServersServerIdDeployRoute
  '/$slug/servers/private': typeof AuthSlugDashServersListPrivateRoute
  '/$slug/servers/public': typeof AuthSlugDashServersListPublicRoute
  '/$slug/servers/$serverId/analytics': typeof AuthSlugDashServersServerIdServerAnalyticsRoute
  '/$slug/servers/$serverId/readme': typeof AuthSlugDashServersServerIdServerReadmeRoute
  '/$slug/servers/$serverId/settings': typeof AuthSlugDashServersServerIdServerSettingsRoute
  '/$slug/servers/$serverId/deployments/preview': typeof AuthSlugDashServersServerIdServerDeploymentsPreviewRoute
  '/$slug/servers/$serverId/deployments/production': typeof AuthSlugDashServersServerIdServerDeploymentsProductionRoute
  '/$slug/servers/$serverId/deployments': typeof AuthSlugDashServersServerIdServerDeploymentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/$slug': typeof AuthSlugRouteRouteWithChildren
  '/github/installed': typeof GithubInstalledRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/$slug/_dash': typeof AuthSlugDashRouteRouteWithChildren
  '/_auth/users/$username': typeof AuthUsersUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/installs': typeof ApiGithubInstallsRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/sync/v1': typeof ApiSyncV1Route
  '/_auth/$slug/_dash/settings': typeof AuthSlugDashSettingsRouteRouteWithChildren
  '/_auth/$slug/deployments/$deploymentId': typeof AuthSlugDeploymentsDeploymentIdRouteRouteWithChildren
  '/_auth/$slug/_dash/deployments': typeof AuthSlugDashDeploymentsRouteWithChildren
  '/api/servers/$serverId/readme': typeof ApiServersServerIdReadmeRoute
  '/_auth/$slug/_dash/': typeof AuthSlugDashIndexRoute
  '/_auth/$slug/_dash/servers': typeof AuthSlugDashServersRouteWithChildren
  '/_auth/$slug/_dash/servers/_list': typeof AuthSlugDashServersListRouteRouteWithChildren
  '/_auth/$slug/_dash/deployments/preview': typeof AuthSlugDashDeploymentsPreviewRoute
  '/_auth/$slug/_dash/deployments/production': typeof AuthSlugDashDeploymentsProductionRoute
  '/_auth/$slug/_dash/servers/import': typeof AuthSlugDashServersImportRoute
  '/_auth/$slug/_dash/servers/new': typeof AuthSlugDashServersNewRoute
  '/_auth/$slug/_dash/settings/github': typeof AuthSlugDashSettingsGithubRoute
  '/_auth/$slug/_dash/settings/webhooks': typeof AuthSlugDashSettingsWebhooksRoute
  '/_auth/$slug/deployments/$deploymentId/logs': typeof AuthSlugDeploymentsDeploymentIdLogsRoute
  '/_auth/$slug/_dash/deployments/': typeof AuthSlugDashDeploymentsIndexRoute
  '/_auth/$slug/_dash/settings/': typeof AuthSlugDashSettingsIndexRoute
  '/_auth/$slug/deployments/$deploymentId/': typeof AuthSlugDeploymentsDeploymentIdIndexRoute
  '/_auth/$slug/_dash/servers/$serverId': typeof AuthSlugDashServersServerIdRouteWithChildren
  '/_auth/$slug/_dash/servers/$serverId/_server': typeof AuthSlugDashServersServerIdServerRouteRouteWithChildren
  '/_auth/$slug/_dash/servers/$serverId/deploy': typeof AuthSlugDashServersServerIdDeployRoute
  '/_auth/$slug/_dash/servers/_list/private': typeof AuthSlugDashServersListPrivateRoute
  '/_auth/$slug/_dash/servers/_list/public': typeof AuthSlugDashServersListPublicRoute
  '/_auth/$slug/_dash/servers/_list/': typeof AuthSlugDashServersListIndexRoute
  '/_auth/$slug/_dash/servers/$serverId/_server/analytics': typeof AuthSlugDashServersServerIdServerAnalyticsRoute
  '/_auth/$slug/_dash/servers/$serverId/_server/deployments': typeof AuthSlugDashServersServerIdServerDeploymentsRouteWithChildren
  '/_auth/$slug/_dash/servers/$serverId/_server/readme': typeof AuthSlugDashServersServerIdServerReadmeRoute
  '/_auth/$slug/_dash/servers/$serverId/_server/settings': typeof AuthSlugDashServersServerIdServerSettingsRoute
  '/_auth/$slug/_dash/servers/$serverId/_server/': typeof AuthSlugDashServersServerIdServerIndexRoute
  '/_auth/$slug/_dash/servers/$serverId/_server/deployments/preview': typeof AuthSlugDashServersServerIdServerDeploymentsPreviewRoute
  '/_auth/$slug/_dash/servers/$serverId/_server/deployments/production': typeof AuthSlugDashServersServerIdServerDeploymentsProductionRoute
  '/_auth/$slug/_dash/servers/$serverId/_server/deployments/': typeof AuthSlugDashServersServerIdServerDeploymentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/$slug'
    | '/github/installed'
    | '/'
    | '/users/$username'
    | '/api/auth/$'
    | '/api/github/callback'
    | '/api/github/installs'
    | '/api/github/repos'
    | '/api/sync/v1'
    | '/$slug/settings'
    | '/$slug/deployments/$deploymentId'
    | '/$slug/deployments'
    | '/api/servers/$serverId/readme'
    | '/$slug/'
    | '/$slug/servers'
    | '/$slug/deployments/preview'
    | '/$slug/deployments/production'
    | '/$slug/servers/import'
    | '/$slug/servers/new'
    | '/$slug/settings/github'
    | '/$slug/settings/webhooks'
    | '/$slug/deployments/$deploymentId/logs'
    | '/$slug/deployments/'
    | '/$slug/settings/'
    | '/$slug/deployments/$deploymentId/'
    | '/$slug/servers/$serverId'
    | '/$slug/servers/$serverId/deploy'
    | '/$slug/servers/private'
    | '/$slug/servers/public'
    | '/$slug/servers/'
    | '/$slug/servers/$serverId/analytics'
    | '/$slug/servers/$serverId/deployments'
    | '/$slug/servers/$serverId/readme'
    | '/$slug/servers/$serverId/settings'
    | '/$slug/servers/$serverId/'
    | '/$slug/servers/$serverId/deployments/preview'
    | '/$slug/servers/$serverId/deployments/production'
    | '/$slug/servers/$serverId/deployments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$slug'
    | '/github/installed'
    | '/'
    | '/users/$username'
    | '/api/auth/$'
    | '/api/github/callback'
    | '/api/github/installs'
    | '/api/github/repos'
    | '/api/sync/v1'
    | '/api/servers/$serverId/readme'
    | '/$slug/servers'
    | '/$slug/deployments/preview'
    | '/$slug/deployments/production'
    | '/$slug/servers/import'
    | '/$slug/servers/new'
    | '/$slug/settings/github'
    | '/$slug/settings/webhooks'
    | '/$slug/deployments/$deploymentId/logs'
    | '/$slug/deployments'
    | '/$slug/settings'
    | '/$slug/deployments/$deploymentId'
    | '/$slug/servers/$serverId'
    | '/$slug/servers/$serverId/deploy'
    | '/$slug/servers/private'
    | '/$slug/servers/public'
    | '/$slug/servers/$serverId/analytics'
    | '/$slug/servers/$serverId/readme'
    | '/$slug/servers/$serverId/settings'
    | '/$slug/servers/$serverId/deployments/preview'
    | '/$slug/servers/$serverId/deployments/production'
    | '/$slug/servers/$serverId/deployments'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/$slug'
    | '/github/installed'
    | '/_auth/'
    | '/_auth/$slug/_dash'
    | '/_auth/users/$username'
    | '/api/auth/$'
    | '/api/github/callback'
    | '/api/github/installs'
    | '/api/github/repos'
    | '/api/sync/v1'
    | '/_auth/$slug/_dash/settings'
    | '/_auth/$slug/deployments/$deploymentId'
    | '/_auth/$slug/_dash/deployments'
    | '/api/servers/$serverId/readme'
    | '/_auth/$slug/_dash/'
    | '/_auth/$slug/_dash/servers'
    | '/_auth/$slug/_dash/servers/_list'
    | '/_auth/$slug/_dash/deployments/preview'
    | '/_auth/$slug/_dash/deployments/production'
    | '/_auth/$slug/_dash/servers/import'
    | '/_auth/$slug/_dash/servers/new'
    | '/_auth/$slug/_dash/settings/github'
    | '/_auth/$slug/_dash/settings/webhooks'
    | '/_auth/$slug/deployments/$deploymentId/logs'
    | '/_auth/$slug/_dash/deployments/'
    | '/_auth/$slug/_dash/settings/'
    | '/_auth/$slug/deployments/$deploymentId/'
    | '/_auth/$slug/_dash/servers/$serverId'
    | '/_auth/$slug/_dash/servers/$serverId/_server'
    | '/_auth/$slug/_dash/servers/$serverId/deploy'
    | '/_auth/$slug/_dash/servers/_list/private'
    | '/_auth/$slug/_dash/servers/_list/public'
    | '/_auth/$slug/_dash/servers/_list/'
    | '/_auth/$slug/_dash/servers/$serverId/_server/analytics'
    | '/_auth/$slug/_dash/servers/$serverId/_server/deployments'
    | '/_auth/$slug/_dash/servers/$serverId/_server/readme'
    | '/_auth/$slug/_dash/servers/$serverId/_server/settings'
    | '/_auth/$slug/_dash/servers/$serverId/_server/'
    | '/_auth/$slug/_dash/servers/$serverId/_server/deployments/preview'
    | '/_auth/$slug/_dash/servers/$serverId/_server/deployments/production'
    | '/_auth/$slug/_dash/servers/$serverId/_server/deployments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  GithubInstalledRoute: typeof GithubInstalledRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGithubCallbackRoute: typeof ApiGithubCallbackRoute
  ApiGithubInstallsRoute: typeof ApiGithubInstallsRoute
  ApiGithubReposRoute: typeof ApiGithubReposRoute
  ApiSyncV1Route: typeof ApiSyncV1Route
  ApiServersServerIdReadmeRoute: typeof ApiServersServerIdReadmeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/github/installed': {
      id: '/github/installed'
      path: '/github/installed'
      fullPath: '/github/installed'
      preLoaderRoute: typeof GithubInstalledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/$slug': {
      id: '/_auth/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof AuthSlugRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/sync/v1': {
      id: '/api/sync/v1'
      path: '/api/sync/v1'
      fullPath: '/api/sync/v1'
      preLoaderRoute: typeof ApiSyncV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/repos': {
      id: '/api/github/repos'
      path: '/api/github/repos'
      fullPath: '/api/github/repos'
      preLoaderRoute: typeof ApiGithubReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/installs': {
      id: '/api/github/installs'
      path: '/api/github/installs'
      fullPath: '/api/github/installs'
      preLoaderRoute: typeof ApiGithubInstallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/callback': {
      id: '/api/github/callback'
      path: '/api/github/callback'
      fullPath: '/api/github/callback'
      preLoaderRoute: typeof ApiGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/users/$username': {
      id: '/_auth/users/$username'
      path: '/users/$username'
      fullPath: '/users/$username'
      preLoaderRoute: typeof AuthUsersUsernameRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/$slug/_dash': {
      id: '/_auth/$slug/_dash'
      path: ''
      fullPath: '/$slug'
      preLoaderRoute: typeof AuthSlugDashRouteRouteImport
      parentRoute: typeof AuthSlugRouteRoute
    }
    '/_auth/$slug/_dash/servers': {
      id: '/_auth/$slug/_dash/servers'
      path: '/servers'
      fullPath: '/$slug/servers'
      preLoaderRoute: typeof AuthSlugDashServersRouteImport
      parentRoute: typeof AuthSlugDashRouteRoute
    }
    '/_auth/$slug/_dash/': {
      id: '/_auth/$slug/_dash/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof AuthSlugDashIndexRouteImport
      parentRoute: typeof AuthSlugDashRouteRoute
    }
    '/api/servers/$serverId/readme': {
      id: '/api/servers/$serverId/readme'
      path: '/api/servers/$serverId/readme'
      fullPath: '/api/servers/$serverId/readme'
      preLoaderRoute: typeof ApiServersServerIdReadmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/$slug/_dash/deployments': {
      id: '/_auth/$slug/_dash/deployments'
      path: '/deployments'
      fullPath: '/$slug/deployments'
      preLoaderRoute: typeof AuthSlugDashDeploymentsRouteImport
      parentRoute: typeof AuthSlugDashRouteRoute
    }
    '/_auth/$slug/deployments/$deploymentId': {
      id: '/_auth/$slug/deployments/$deploymentId'
      path: '/deployments/$deploymentId'
      fullPath: '/$slug/deployments/$deploymentId'
      preLoaderRoute: typeof AuthSlugDeploymentsDeploymentIdRouteRouteImport
      parentRoute: typeof AuthSlugRouteRoute
    }
    '/_auth/$slug/_dash/settings': {
      id: '/_auth/$slug/_dash/settings'
      path: '/settings'
      fullPath: '/$slug/settings'
      preLoaderRoute: typeof AuthSlugDashSettingsRouteRouteImport
      parentRoute: typeof AuthSlugDashRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId': {
      id: '/_auth/$slug/_dash/servers/$serverId'
      path: '/$serverId'
      fullPath: '/$slug/servers/$serverId'
      preLoaderRoute: typeof AuthSlugDashServersServerIdRouteImport
      parentRoute: typeof AuthSlugDashServersRoute
    }
    '/_auth/$slug/deployments/$deploymentId/': {
      id: '/_auth/$slug/deployments/$deploymentId/'
      path: '/'
      fullPath: '/$slug/deployments/$deploymentId/'
      preLoaderRoute: typeof AuthSlugDeploymentsDeploymentIdIndexRouteImport
      parentRoute: typeof AuthSlugDeploymentsDeploymentIdRouteRoute
    }
    '/_auth/$slug/_dash/settings/': {
      id: '/_auth/$slug/_dash/settings/'
      path: '/'
      fullPath: '/$slug/settings/'
      preLoaderRoute: typeof AuthSlugDashSettingsIndexRouteImport
      parentRoute: typeof AuthSlugDashSettingsRouteRoute
    }
    '/_auth/$slug/_dash/deployments/': {
      id: '/_auth/$slug/_dash/deployments/'
      path: '/'
      fullPath: '/$slug/deployments/'
      preLoaderRoute: typeof AuthSlugDashDeploymentsIndexRouteImport
      parentRoute: typeof AuthSlugDashDeploymentsRoute
    }
    '/_auth/$slug/deployments/$deploymentId/logs': {
      id: '/_auth/$slug/deployments/$deploymentId/logs'
      path: '/logs'
      fullPath: '/$slug/deployments/$deploymentId/logs'
      preLoaderRoute: typeof AuthSlugDeploymentsDeploymentIdLogsRouteImport
      parentRoute: typeof AuthSlugDeploymentsDeploymentIdRouteRoute
    }
    '/_auth/$slug/_dash/settings/webhooks': {
      id: '/_auth/$slug/_dash/settings/webhooks'
      path: '/webhooks'
      fullPath: '/$slug/settings/webhooks'
      preLoaderRoute: typeof AuthSlugDashSettingsWebhooksRouteImport
      parentRoute: typeof AuthSlugDashSettingsRouteRoute
    }
    '/_auth/$slug/_dash/settings/github': {
      id: '/_auth/$slug/_dash/settings/github'
      path: '/github'
      fullPath: '/$slug/settings/github'
      preLoaderRoute: typeof AuthSlugDashSettingsGithubRouteImport
      parentRoute: typeof AuthSlugDashSettingsRouteRoute
    }
    '/_auth/$slug/_dash/servers/new': {
      id: '/_auth/$slug/_dash/servers/new'
      path: '/new'
      fullPath: '/$slug/servers/new'
      preLoaderRoute: typeof AuthSlugDashServersNewRouteImport
      parentRoute: typeof AuthSlugDashServersRoute
    }
    '/_auth/$slug/_dash/servers/import': {
      id: '/_auth/$slug/_dash/servers/import'
      path: '/import'
      fullPath: '/$slug/servers/import'
      preLoaderRoute: typeof AuthSlugDashServersImportRouteImport
      parentRoute: typeof AuthSlugDashServersRoute
    }
    '/_auth/$slug/_dash/deployments/production': {
      id: '/_auth/$slug/_dash/deployments/production'
      path: '/production'
      fullPath: '/$slug/deployments/production'
      preLoaderRoute: typeof AuthSlugDashDeploymentsProductionRouteImport
      parentRoute: typeof AuthSlugDashDeploymentsRoute
    }
    '/_auth/$slug/_dash/deployments/preview': {
      id: '/_auth/$slug/_dash/deployments/preview'
      path: '/preview'
      fullPath: '/$slug/deployments/preview'
      preLoaderRoute: typeof AuthSlugDashDeploymentsPreviewRouteImport
      parentRoute: typeof AuthSlugDashDeploymentsRoute
    }
    '/_auth/$slug/_dash/servers/_list': {
      id: '/_auth/$slug/_dash/servers/_list'
      path: '/servers'
      fullPath: '/$slug/servers'
      preLoaderRoute: typeof AuthSlugDashServersListRouteRouteImport
      parentRoute: typeof AuthSlugDashServersRoute
    }
    '/_auth/$slug/_dash/servers/_list/': {
      id: '/_auth/$slug/_dash/servers/_list/'
      path: '/'
      fullPath: '/$slug/servers/'
      preLoaderRoute: typeof AuthSlugDashServersListIndexRouteImport
      parentRoute: typeof AuthSlugDashServersListRouteRoute
    }
    '/_auth/$slug/_dash/servers/_list/public': {
      id: '/_auth/$slug/_dash/servers/_list/public'
      path: '/public'
      fullPath: '/$slug/servers/public'
      preLoaderRoute: typeof AuthSlugDashServersListPublicRouteImport
      parentRoute: typeof AuthSlugDashServersListRouteRoute
    }
    '/_auth/$slug/_dash/servers/_list/private': {
      id: '/_auth/$slug/_dash/servers/_list/private'
      path: '/private'
      fullPath: '/$slug/servers/private'
      preLoaderRoute: typeof AuthSlugDashServersListPrivateRouteImport
      parentRoute: typeof AuthSlugDashServersListRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/deploy': {
      id: '/_auth/$slug/_dash/servers/$serverId/deploy'
      path: '/deploy'
      fullPath: '/$slug/servers/$serverId/deploy'
      preLoaderRoute: typeof AuthSlugDashServersServerIdDeployRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/_server': {
      id: '/_auth/$slug/_dash/servers/$serverId/_server'
      path: '/$serverId'
      fullPath: '/$slug/servers/$serverId'
      preLoaderRoute: typeof AuthSlugDashServersServerIdServerRouteRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/_server/': {
      id: '/_auth/$slug/_dash/servers/$serverId/_server/'
      path: '/'
      fullPath: '/$slug/servers/$serverId/'
      preLoaderRoute: typeof AuthSlugDashServersServerIdServerIndexRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdServerRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/_server/settings': {
      id: '/_auth/$slug/_dash/servers/$serverId/_server/settings'
      path: '/settings'
      fullPath: '/$slug/servers/$serverId/settings'
      preLoaderRoute: typeof AuthSlugDashServersServerIdServerSettingsRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdServerRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/_server/readme': {
      id: '/_auth/$slug/_dash/servers/$serverId/_server/readme'
      path: '/readme'
      fullPath: '/$slug/servers/$serverId/readme'
      preLoaderRoute: typeof AuthSlugDashServersServerIdServerReadmeRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdServerRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/_server/deployments': {
      id: '/_auth/$slug/_dash/servers/$serverId/_server/deployments'
      path: '/deployments'
      fullPath: '/$slug/servers/$serverId/deployments'
      preLoaderRoute: typeof AuthSlugDashServersServerIdServerDeploymentsRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdServerRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/_server/analytics': {
      id: '/_auth/$slug/_dash/servers/$serverId/_server/analytics'
      path: '/analytics'
      fullPath: '/$slug/servers/$serverId/analytics'
      preLoaderRoute: typeof AuthSlugDashServersServerIdServerAnalyticsRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdServerRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/_server/deployments/': {
      id: '/_auth/$slug/_dash/servers/$serverId/_server/deployments/'
      path: '/'
      fullPath: '/$slug/servers/$serverId/deployments/'
      preLoaderRoute: typeof AuthSlugDashServersServerIdServerDeploymentsIndexRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdServerDeploymentsRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/_server/deployments/production': {
      id: '/_auth/$slug/_dash/servers/$serverId/_server/deployments/production'
      path: '/production'
      fullPath: '/$slug/servers/$serverId/deployments/production'
      preLoaderRoute: typeof AuthSlugDashServersServerIdServerDeploymentsProductionRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdServerDeploymentsRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/_server/deployments/preview': {
      id: '/_auth/$slug/_dash/servers/$serverId/_server/deployments/preview'
      path: '/preview'
      fullPath: '/$slug/servers/$serverId/deployments/preview'
      preLoaderRoute: typeof AuthSlugDashServersServerIdServerDeploymentsPreviewRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdServerDeploymentsRoute
    }
  }
}

interface AuthSlugDashSettingsRouteRouteChildren {
  AuthSlugDashSettingsGithubRoute: typeof AuthSlugDashSettingsGithubRoute
  AuthSlugDashSettingsWebhooksRoute: typeof AuthSlugDashSettingsWebhooksRoute
  AuthSlugDashSettingsIndexRoute: typeof AuthSlugDashSettingsIndexRoute
}

const AuthSlugDashSettingsRouteRouteChildren: AuthSlugDashSettingsRouteRouteChildren =
  {
    AuthSlugDashSettingsGithubRoute: AuthSlugDashSettingsGithubRoute,
    AuthSlugDashSettingsWebhooksRoute: AuthSlugDashSettingsWebhooksRoute,
    AuthSlugDashSettingsIndexRoute: AuthSlugDashSettingsIndexRoute,
  }

const AuthSlugDashSettingsRouteRouteWithChildren =
  AuthSlugDashSettingsRouteRoute._addFileChildren(
    AuthSlugDashSettingsRouteRouteChildren,
  )

interface AuthSlugDashDeploymentsRouteChildren {
  AuthSlugDashDeploymentsPreviewRoute: typeof AuthSlugDashDeploymentsPreviewRoute
  AuthSlugDashDeploymentsProductionRoute: typeof AuthSlugDashDeploymentsProductionRoute
  AuthSlugDashDeploymentsIndexRoute: typeof AuthSlugDashDeploymentsIndexRoute
}

const AuthSlugDashDeploymentsRouteChildren: AuthSlugDashDeploymentsRouteChildren =
  {
    AuthSlugDashDeploymentsPreviewRoute: AuthSlugDashDeploymentsPreviewRoute,
    AuthSlugDashDeploymentsProductionRoute:
      AuthSlugDashDeploymentsProductionRoute,
    AuthSlugDashDeploymentsIndexRoute: AuthSlugDashDeploymentsIndexRoute,
  }

const AuthSlugDashDeploymentsRouteWithChildren =
  AuthSlugDashDeploymentsRoute._addFileChildren(
    AuthSlugDashDeploymentsRouteChildren,
  )

interface AuthSlugDashServersListRouteRouteChildren {
  AuthSlugDashServersListPrivateRoute: typeof AuthSlugDashServersListPrivateRoute
  AuthSlugDashServersListPublicRoute: typeof AuthSlugDashServersListPublicRoute
  AuthSlugDashServersListIndexRoute: typeof AuthSlugDashServersListIndexRoute
}

const AuthSlugDashServersListRouteRouteChildren: AuthSlugDashServersListRouteRouteChildren =
  {
    AuthSlugDashServersListPrivateRoute: AuthSlugDashServersListPrivateRoute,
    AuthSlugDashServersListPublicRoute: AuthSlugDashServersListPublicRoute,
    AuthSlugDashServersListIndexRoute: AuthSlugDashServersListIndexRoute,
  }

const AuthSlugDashServersListRouteRouteWithChildren =
  AuthSlugDashServersListRouteRoute._addFileChildren(
    AuthSlugDashServersListRouteRouteChildren,
  )

interface AuthSlugDashServersServerIdServerDeploymentsRouteChildren {
  AuthSlugDashServersServerIdServerDeploymentsPreviewRoute: typeof AuthSlugDashServersServerIdServerDeploymentsPreviewRoute
  AuthSlugDashServersServerIdServerDeploymentsProductionRoute: typeof AuthSlugDashServersServerIdServerDeploymentsProductionRoute
  AuthSlugDashServersServerIdServerDeploymentsIndexRoute: typeof AuthSlugDashServersServerIdServerDeploymentsIndexRoute
}

const AuthSlugDashServersServerIdServerDeploymentsRouteChildren: AuthSlugDashServersServerIdServerDeploymentsRouteChildren =
  {
    AuthSlugDashServersServerIdServerDeploymentsPreviewRoute:
      AuthSlugDashServersServerIdServerDeploymentsPreviewRoute,
    AuthSlugDashServersServerIdServerDeploymentsProductionRoute:
      AuthSlugDashServersServerIdServerDeploymentsProductionRoute,
    AuthSlugDashServersServerIdServerDeploymentsIndexRoute:
      AuthSlugDashServersServerIdServerDeploymentsIndexRoute,
  }

const AuthSlugDashServersServerIdServerDeploymentsRouteWithChildren =
  AuthSlugDashServersServerIdServerDeploymentsRoute._addFileChildren(
    AuthSlugDashServersServerIdServerDeploymentsRouteChildren,
  )

interface AuthSlugDashServersServerIdServerRouteRouteChildren {
  AuthSlugDashServersServerIdServerAnalyticsRoute: typeof AuthSlugDashServersServerIdServerAnalyticsRoute
  AuthSlugDashServersServerIdServerDeploymentsRoute: typeof AuthSlugDashServersServerIdServerDeploymentsRouteWithChildren
  AuthSlugDashServersServerIdServerReadmeRoute: typeof AuthSlugDashServersServerIdServerReadmeRoute
  AuthSlugDashServersServerIdServerSettingsRoute: typeof AuthSlugDashServersServerIdServerSettingsRoute
  AuthSlugDashServersServerIdServerIndexRoute: typeof AuthSlugDashServersServerIdServerIndexRoute
}

const AuthSlugDashServersServerIdServerRouteRouteChildren: AuthSlugDashServersServerIdServerRouteRouteChildren =
  {
    AuthSlugDashServersServerIdServerAnalyticsRoute:
      AuthSlugDashServersServerIdServerAnalyticsRoute,
    AuthSlugDashServersServerIdServerDeploymentsRoute:
      AuthSlugDashServersServerIdServerDeploymentsRouteWithChildren,
    AuthSlugDashServersServerIdServerReadmeRoute:
      AuthSlugDashServersServerIdServerReadmeRoute,
    AuthSlugDashServersServerIdServerSettingsRoute:
      AuthSlugDashServersServerIdServerSettingsRoute,
    AuthSlugDashServersServerIdServerIndexRoute:
      AuthSlugDashServersServerIdServerIndexRoute,
  }

const AuthSlugDashServersServerIdServerRouteRouteWithChildren =
  AuthSlugDashServersServerIdServerRouteRoute._addFileChildren(
    AuthSlugDashServersServerIdServerRouteRouteChildren,
  )

interface AuthSlugDashServersServerIdRouteChildren {
  AuthSlugDashServersServerIdServerRouteRoute: typeof AuthSlugDashServersServerIdServerRouteRouteWithChildren
  AuthSlugDashServersServerIdDeployRoute: typeof AuthSlugDashServersServerIdDeployRoute
}

const AuthSlugDashServersServerIdRouteChildren: AuthSlugDashServersServerIdRouteChildren =
  {
    AuthSlugDashServersServerIdServerRouteRoute:
      AuthSlugDashServersServerIdServerRouteRouteWithChildren,
    AuthSlugDashServersServerIdDeployRoute:
      AuthSlugDashServersServerIdDeployRoute,
  }

const AuthSlugDashServersServerIdRouteWithChildren =
  AuthSlugDashServersServerIdRoute._addFileChildren(
    AuthSlugDashServersServerIdRouteChildren,
  )

interface AuthSlugDashServersRouteChildren {
  AuthSlugDashServersListRouteRoute: typeof AuthSlugDashServersListRouteRouteWithChildren
  AuthSlugDashServersImportRoute: typeof AuthSlugDashServersImportRoute
  AuthSlugDashServersNewRoute: typeof AuthSlugDashServersNewRoute
  AuthSlugDashServersServerIdRoute: typeof AuthSlugDashServersServerIdRouteWithChildren
}

const AuthSlugDashServersRouteChildren: AuthSlugDashServersRouteChildren = {
  AuthSlugDashServersListRouteRoute:
    AuthSlugDashServersListRouteRouteWithChildren,
  AuthSlugDashServersImportRoute: AuthSlugDashServersImportRoute,
  AuthSlugDashServersNewRoute: AuthSlugDashServersNewRoute,
  AuthSlugDashServersServerIdRoute:
    AuthSlugDashServersServerIdRouteWithChildren,
}

const AuthSlugDashServersRouteWithChildren =
  AuthSlugDashServersRoute._addFileChildren(AuthSlugDashServersRouteChildren)

interface AuthSlugDashRouteRouteChildren {
  AuthSlugDashSettingsRouteRoute: typeof AuthSlugDashSettingsRouteRouteWithChildren
  AuthSlugDashDeploymentsRoute: typeof AuthSlugDashDeploymentsRouteWithChildren
  AuthSlugDashIndexRoute: typeof AuthSlugDashIndexRoute
  AuthSlugDashServersRoute: typeof AuthSlugDashServersRouteWithChildren
}

const AuthSlugDashRouteRouteChildren: AuthSlugDashRouteRouteChildren = {
  AuthSlugDashSettingsRouteRoute: AuthSlugDashSettingsRouteRouteWithChildren,
  AuthSlugDashDeploymentsRoute: AuthSlugDashDeploymentsRouteWithChildren,
  AuthSlugDashIndexRoute: AuthSlugDashIndexRoute,
  AuthSlugDashServersRoute: AuthSlugDashServersRouteWithChildren,
}

const AuthSlugDashRouteRouteWithChildren =
  AuthSlugDashRouteRoute._addFileChildren(AuthSlugDashRouteRouteChildren)

interface AuthSlugDeploymentsDeploymentIdRouteRouteChildren {
  AuthSlugDeploymentsDeploymentIdLogsRoute: typeof AuthSlugDeploymentsDeploymentIdLogsRoute
  AuthSlugDeploymentsDeploymentIdIndexRoute: typeof AuthSlugDeploymentsDeploymentIdIndexRoute
}

const AuthSlugDeploymentsDeploymentIdRouteRouteChildren: AuthSlugDeploymentsDeploymentIdRouteRouteChildren =
  {
    AuthSlugDeploymentsDeploymentIdLogsRoute:
      AuthSlugDeploymentsDeploymentIdLogsRoute,
    AuthSlugDeploymentsDeploymentIdIndexRoute:
      AuthSlugDeploymentsDeploymentIdIndexRoute,
  }

const AuthSlugDeploymentsDeploymentIdRouteRouteWithChildren =
  AuthSlugDeploymentsDeploymentIdRouteRoute._addFileChildren(
    AuthSlugDeploymentsDeploymentIdRouteRouteChildren,
  )

interface AuthSlugRouteRouteChildren {
  AuthSlugDashRouteRoute: typeof AuthSlugDashRouteRouteWithChildren
  AuthSlugDeploymentsDeploymentIdRouteRoute: typeof AuthSlugDeploymentsDeploymentIdRouteRouteWithChildren
}

const AuthSlugRouteRouteChildren: AuthSlugRouteRouteChildren = {
  AuthSlugDashRouteRoute: AuthSlugDashRouteRouteWithChildren,
  AuthSlugDeploymentsDeploymentIdRouteRoute:
    AuthSlugDeploymentsDeploymentIdRouteRouteWithChildren,
}

const AuthSlugRouteRouteWithChildren = AuthSlugRouteRoute._addFileChildren(
  AuthSlugRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSlugRouteRoute: typeof AuthSlugRouteRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  AuthUsersUsernameRoute: typeof AuthUsersUsernameRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSlugRouteRoute: AuthSlugRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  AuthUsersUsernameRoute: AuthUsersUsernameRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  GithubInstalledRoute: GithubInstalledRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGithubCallbackRoute: ApiGithubCallbackRoute,
  ApiGithubInstallsRoute: ApiGithubInstallsRoute,
  ApiGithubReposRoute: ApiGithubReposRoute,
  ApiSyncV1Route: ApiSyncV1Route,
  ApiServersServerIdReadmeRoute: ApiServersServerIdReadmeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
