/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as GithubInstalledRouteImport } from './routes/github/installed'
import { Route as AuthSlugRouteRouteImport } from './routes/_auth/$slug/route'
import { Route as ApiSyncV1RouteImport } from './routes/api/sync/v1'
import { Route as ApiGithubReposRouteImport } from './routes/api/github.repos'
import { Route as ApiGithubInstallsRouteImport } from './routes/api/github.installs'
import { Route as ApiGithubCallbackRouteImport } from './routes/api/github.callback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthSlugDashRouteRouteImport } from './routes/_auth/$slug/_dash/route'
import { Route as AuthSlugDashIndexRouteImport } from './routes/_auth/$slug/_dash/index'
import { Route as ApiServersServerIdReadmeRouteImport } from './routes/api/servers/$serverId.readme'
import { Route as AuthSlugDashSettingsRouteRouteImport } from './routes/_auth/$slug/_dash/settings/route'
import { Route as AuthSlugDashSettingsIndexRouteImport } from './routes/_auth/$slug/_dash/settings/index'
import { Route as AuthSlugDashSettingsWebhooksRouteImport } from './routes/_auth/$slug/_dash/settings/webhooks'
import { Route as AuthSlugDashSettingsGithubRouteImport } from './routes/_auth/$slug/_dash/settings/github'
import { Route as AuthSlugDashServersNewRouteImport } from './routes/_auth/$slug/_dash/servers/new'
import { Route as AuthSlugDashServersImportRouteImport } from './routes/_auth/$slug/_dash/servers/import'
import { Route as AuthSlugDashServersListRouteRouteImport } from './routes/_auth/$slug/_dash/servers/_list/route'
import { Route as AuthSlugDashServersServerIdRouteRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/route'
import { Route as AuthSlugDashDeploymentsListRouteRouteImport } from './routes/_auth/$slug/_dash/deployments/_list/route'
import { Route as AuthSlugDashDeploymentsDeploymentIdRouteRouteImport } from './routes/_auth/$slug/_dash/deployments/$deploymentId/route'
import { Route as AuthSlugDashServersListIndexRouteImport } from './routes/_auth/$slug/_dash/servers/_list/index'
import { Route as AuthSlugDashDeploymentsListIndexRouteImport } from './routes/_auth/$slug/_dash/deployments/_list/index'
import { Route as AuthSlugDashDeploymentsDeploymentIdIndexRouteImport } from './routes/_auth/$slug/_dash/deployments/$deploymentId/index'
import { Route as AuthSlugDashServersListPublicRouteImport } from './routes/_auth/$slug/_dash/servers/_list/public'
import { Route as AuthSlugDashServersListPrivateRouteImport } from './routes/_auth/$slug/_dash/servers/_list/private'
import { Route as AuthSlugDashServersServerIdDeployRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/deploy'
import { Route as AuthSlugDashDeploymentsListProductionRouteImport } from './routes/_auth/$slug/_dash/deployments/_list/production'
import { Route as AuthSlugDashDeploymentsListPreviewRouteImport } from './routes/_auth/$slug/_dash/deployments/_list/preview'
import { Route as AuthSlugDashDeploymentsDeploymentIdLogsRouteImport } from './routes/_auth/$slug/_dash/deployments/$deploymentId/logs'
import { Route as AuthSlugDashServersServerIdDetailRouteRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/_detail/route'
import { Route as AuthSlugDashServersServerIdDetailIndexRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/_detail/index'
import { Route as AuthSlugDashServersServerIdDetailSettingsRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/_detail/settings'
import { Route as AuthSlugDashServersServerIdDetailReadmeRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/_detail/readme'
import { Route as AuthSlugDashServersServerIdDetailAnalyticsRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/_detail/analytics'
import { Route as AuthSlugDashServersServerIdDetailDeploymentsRouteRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/_detail/deployments/route'
import { Route as AuthSlugDashServersServerIdDetailDeploymentsIndexRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/_detail/deployments/index'
import { Route as AuthSlugDashServersServerIdDetailDeploymentsProductionRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/_detail/deployments/production'
import { Route as AuthSlugDashServersServerIdDetailDeploymentsPreviewRouteImport } from './routes/_auth/$slug/_dash/servers/$serverId/_detail/deployments/preview'

const AuthSlugDashServersRouteImport = createFileRoute(
  '/_auth/$slug/_dash/servers',
)()
const AuthSlugDashDeploymentsRouteImport = createFileRoute(
  '/_auth/$slug/_dash/deployments',
)()

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const GithubInstalledRoute = GithubInstalledRouteImport.update({
  id: '/github/installed',
  path: '/github/installed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSlugRouteRoute = AuthSlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiSyncV1Route = ApiSyncV1RouteImport.update({
  id: '/api/sync/v1',
  path: '/api/sync/v1',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubReposRoute = ApiGithubReposRouteImport.update({
  id: '/api/github/repos',
  path: '/api/github/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubInstallsRoute = ApiGithubInstallsRouteImport.update({
  id: '/api/github/installs',
  path: '/api/github/installs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCallbackRoute = ApiGithubCallbackRouteImport.update({
  id: '/api/github/callback',
  path: '/api/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSlugDashRouteRoute = AuthSlugDashRouteRouteImport.update({
  id: '/_dash',
  getParentRoute: () => AuthSlugRouteRoute,
} as any)
const AuthSlugDashServersRoute = AuthSlugDashServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AuthSlugDashRouteRoute,
} as any)
const AuthSlugDashDeploymentsRoute = AuthSlugDashDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => AuthSlugDashRouteRoute,
} as any)
const AuthSlugDashIndexRoute = AuthSlugDashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSlugDashRouteRoute,
} as any)
const ApiServersServerIdReadmeRoute =
  ApiServersServerIdReadmeRouteImport.update({
    id: '/api/servers/$serverId/readme',
    path: '/api/servers/$serverId/readme',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSlugDashSettingsRouteRoute =
  AuthSlugDashSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthSlugDashRouteRoute,
  } as any)
const AuthSlugDashSettingsIndexRoute =
  AuthSlugDashSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthSlugDashSettingsRouteRoute,
  } as any)
const AuthSlugDashSettingsWebhooksRoute =
  AuthSlugDashSettingsWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthSlugDashSettingsRouteRoute,
  } as any)
const AuthSlugDashSettingsGithubRoute =
  AuthSlugDashSettingsGithubRouteImport.update({
    id: '/github',
    path: '/github',
    getParentRoute: () => AuthSlugDashSettingsRouteRoute,
  } as any)
const AuthSlugDashServersNewRoute = AuthSlugDashServersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthSlugDashServersRoute,
} as any)
const AuthSlugDashServersImportRoute =
  AuthSlugDashServersImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthSlugDashServersRoute,
  } as any)
const AuthSlugDashServersListRouteRoute =
  AuthSlugDashServersListRouteRouteImport.update({
    id: '/_list',
    getParentRoute: () => AuthSlugDashServersRoute,
  } as any)
const AuthSlugDashServersServerIdRouteRoute =
  AuthSlugDashServersServerIdRouteRouteImport.update({
    id: '/servers/$serverId',
    path: '/servers/$serverId',
    getParentRoute: () => AuthSlugDashRouteRoute,
  } as any)
const AuthSlugDashDeploymentsListRouteRoute =
  AuthSlugDashDeploymentsListRouteRouteImport.update({
    id: '/_list',
    getParentRoute: () => AuthSlugDashDeploymentsRoute,
  } as any)
const AuthSlugDashDeploymentsDeploymentIdRouteRoute =
  AuthSlugDashDeploymentsDeploymentIdRouteRouteImport.update({
    id: '/deployments/$deploymentId',
    path: '/deployments/$deploymentId',
    getParentRoute: () => AuthSlugDashRouteRoute,
  } as any)
const AuthSlugDashServersListIndexRoute =
  AuthSlugDashServersListIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthSlugDashServersListRouteRoute,
  } as any)
const AuthSlugDashDeploymentsListIndexRoute =
  AuthSlugDashDeploymentsListIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthSlugDashDeploymentsListRouteRoute,
  } as any)
const AuthSlugDashDeploymentsDeploymentIdIndexRoute =
  AuthSlugDashDeploymentsDeploymentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthSlugDashDeploymentsDeploymentIdRouteRoute,
  } as any)
const AuthSlugDashServersListPublicRoute =
  AuthSlugDashServersListPublicRouteImport.update({
    id: '/public',
    path: '/public',
    getParentRoute: () => AuthSlugDashServersListRouteRoute,
  } as any)
const AuthSlugDashServersListPrivateRoute =
  AuthSlugDashServersListPrivateRouteImport.update({
    id: '/private',
    path: '/private',
    getParentRoute: () => AuthSlugDashServersListRouteRoute,
  } as any)
const AuthSlugDashServersServerIdDeployRoute =
  AuthSlugDashServersServerIdDeployRouteImport.update({
    id: '/deploy',
    path: '/deploy',
    getParentRoute: () => AuthSlugDashServersServerIdRouteRoute,
  } as any)
const AuthSlugDashDeploymentsListProductionRoute =
  AuthSlugDashDeploymentsListProductionRouteImport.update({
    id: '/production',
    path: '/production',
    getParentRoute: () => AuthSlugDashDeploymentsListRouteRoute,
  } as any)
const AuthSlugDashDeploymentsListPreviewRoute =
  AuthSlugDashDeploymentsListPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AuthSlugDashDeploymentsListRouteRoute,
  } as any)
const AuthSlugDashDeploymentsDeploymentIdLogsRoute =
  AuthSlugDashDeploymentsDeploymentIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthSlugDashDeploymentsDeploymentIdRouteRoute,
  } as any)
const AuthSlugDashServersServerIdDetailRouteRoute =
  AuthSlugDashServersServerIdDetailRouteRouteImport.update({
    id: '/_detail',
    getParentRoute: () => AuthSlugDashServersServerIdRouteRoute,
  } as any)
const AuthSlugDashServersServerIdDetailIndexRoute =
  AuthSlugDashServersServerIdDetailIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthSlugDashServersServerIdDetailRouteRoute,
  } as any)
const AuthSlugDashServersServerIdDetailSettingsRoute =
  AuthSlugDashServersServerIdDetailSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthSlugDashServersServerIdDetailRouteRoute,
  } as any)
const AuthSlugDashServersServerIdDetailReadmeRoute =
  AuthSlugDashServersServerIdDetailReadmeRouteImport.update({
    id: '/readme',
    path: '/readme',
    getParentRoute: () => AuthSlugDashServersServerIdDetailRouteRoute,
  } as any)
const AuthSlugDashServersServerIdDetailAnalyticsRoute =
  AuthSlugDashServersServerIdDetailAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthSlugDashServersServerIdDetailRouteRoute,
  } as any)
const AuthSlugDashServersServerIdDetailDeploymentsRouteRoute =
  AuthSlugDashServersServerIdDetailDeploymentsRouteRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AuthSlugDashServersServerIdDetailRouteRoute,
  } as any)
const AuthSlugDashServersServerIdDetailDeploymentsIndexRoute =
  AuthSlugDashServersServerIdDetailDeploymentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthSlugDashServersServerIdDetailDeploymentsRouteRoute,
  } as any)
const AuthSlugDashServersServerIdDetailDeploymentsProductionRoute =
  AuthSlugDashServersServerIdDetailDeploymentsProductionRouteImport.update({
    id: '/production',
    path: '/production',
    getParentRoute: () =>
      AuthSlugDashServersServerIdDetailDeploymentsRouteRoute,
  } as any)
const AuthSlugDashServersServerIdDetailDeploymentsPreviewRoute =
  AuthSlugDashServersServerIdDetailDeploymentsPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () =>
      AuthSlugDashServersServerIdDetailDeploymentsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/$slug': typeof AuthSlugDashRouteRouteWithChildren
  '/github/installed': typeof GithubInstalledRoute
  '/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/installs': typeof ApiGithubInstallsRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/sync/v1': typeof ApiSyncV1Route
  '/$slug/settings': typeof AuthSlugDashSettingsRouteRouteWithChildren
  '/api/servers/$serverId/readme': typeof ApiServersServerIdReadmeRoute
  '/$slug/': typeof AuthSlugDashIndexRoute
  '/$slug/deployments/$deploymentId': typeof AuthSlugDashDeploymentsDeploymentIdRouteRouteWithChildren
  '/$slug/deployments': typeof AuthSlugDashDeploymentsListRouteRouteWithChildren
  '/$slug/servers/$serverId': typeof AuthSlugDashServersServerIdDetailRouteRouteWithChildren
  '/$slug/servers': typeof AuthSlugDashServersListRouteRouteWithChildren
  '/$slug/servers/import': typeof AuthSlugDashServersImportRoute
  '/$slug/servers/new': typeof AuthSlugDashServersNewRoute
  '/$slug/settings/github': typeof AuthSlugDashSettingsGithubRoute
  '/$slug/settings/webhooks': typeof AuthSlugDashSettingsWebhooksRoute
  '/$slug/settings/': typeof AuthSlugDashSettingsIndexRoute
  '/$slug/deployments/$deploymentId/logs': typeof AuthSlugDashDeploymentsDeploymentIdLogsRoute
  '/$slug/deployments/preview': typeof AuthSlugDashDeploymentsListPreviewRoute
  '/$slug/deployments/production': typeof AuthSlugDashDeploymentsListProductionRoute
  '/$slug/servers/$serverId/deploy': typeof AuthSlugDashServersServerIdDeployRoute
  '/$slug/servers/private': typeof AuthSlugDashServersListPrivateRoute
  '/$slug/servers/public': typeof AuthSlugDashServersListPublicRoute
  '/$slug/deployments/$deploymentId/': typeof AuthSlugDashDeploymentsDeploymentIdIndexRoute
  '/$slug/deployments/': typeof AuthSlugDashDeploymentsListIndexRoute
  '/$slug/servers/': typeof AuthSlugDashServersListIndexRoute
  '/$slug/servers/$serverId/deployments': typeof AuthSlugDashServersServerIdDetailDeploymentsRouteRouteWithChildren
  '/$slug/servers/$serverId/analytics': typeof AuthSlugDashServersServerIdDetailAnalyticsRoute
  '/$slug/servers/$serverId/readme': typeof AuthSlugDashServersServerIdDetailReadmeRoute
  '/$slug/servers/$serverId/settings': typeof AuthSlugDashServersServerIdDetailSettingsRoute
  '/$slug/servers/$serverId/': typeof AuthSlugDashServersServerIdDetailIndexRoute
  '/$slug/servers/$serverId/deployments/preview': typeof AuthSlugDashServersServerIdDetailDeploymentsPreviewRoute
  '/$slug/servers/$serverId/deployments/production': typeof AuthSlugDashServersServerIdDetailDeploymentsProductionRoute
  '/$slug/servers/$serverId/deployments/': typeof AuthSlugDashServersServerIdDetailDeploymentsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$slug': typeof AuthSlugDashIndexRoute
  '/github/installed': typeof GithubInstalledRoute
  '/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/installs': typeof ApiGithubInstallsRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/sync/v1': typeof ApiSyncV1Route
  '/api/servers/$serverId/readme': typeof ApiServersServerIdReadmeRoute
  '/$slug/deployments': typeof AuthSlugDashDeploymentsListIndexRoute
  '/$slug/servers/$serverId': typeof AuthSlugDashServersServerIdDetailIndexRoute
  '/$slug/servers': typeof AuthSlugDashServersListIndexRoute
  '/$slug/servers/import': typeof AuthSlugDashServersImportRoute
  '/$slug/servers/new': typeof AuthSlugDashServersNewRoute
  '/$slug/settings/github': typeof AuthSlugDashSettingsGithubRoute
  '/$slug/settings/webhooks': typeof AuthSlugDashSettingsWebhooksRoute
  '/$slug/settings': typeof AuthSlugDashSettingsIndexRoute
  '/$slug/deployments/$deploymentId/logs': typeof AuthSlugDashDeploymentsDeploymentIdLogsRoute
  '/$slug/deployments/preview': typeof AuthSlugDashDeploymentsListPreviewRoute
  '/$slug/deployments/production': typeof AuthSlugDashDeploymentsListProductionRoute
  '/$slug/servers/$serverId/deploy': typeof AuthSlugDashServersServerIdDeployRoute
  '/$slug/servers/private': typeof AuthSlugDashServersListPrivateRoute
  '/$slug/servers/public': typeof AuthSlugDashServersListPublicRoute
  '/$slug/deployments/$deploymentId': typeof AuthSlugDashDeploymentsDeploymentIdIndexRoute
  '/$slug/servers/$serverId/analytics': typeof AuthSlugDashServersServerIdDetailAnalyticsRoute
  '/$slug/servers/$serverId/readme': typeof AuthSlugDashServersServerIdDetailReadmeRoute
  '/$slug/servers/$serverId/settings': typeof AuthSlugDashServersServerIdDetailSettingsRoute
  '/$slug/servers/$serverId/deployments/preview': typeof AuthSlugDashServersServerIdDetailDeploymentsPreviewRoute
  '/$slug/servers/$serverId/deployments/production': typeof AuthSlugDashServersServerIdDetailDeploymentsProductionRoute
  '/$slug/servers/$serverId/deployments': typeof AuthSlugDashServersServerIdDetailDeploymentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/$slug': typeof AuthSlugRouteRouteWithChildren
  '/github/installed': typeof GithubInstalledRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/$slug/_dash': typeof AuthSlugDashRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/installs': typeof ApiGithubInstallsRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/sync/v1': typeof ApiSyncV1Route
  '/_auth/$slug/_dash/settings': typeof AuthSlugDashSettingsRouteRouteWithChildren
  '/api/servers/$serverId/readme': typeof ApiServersServerIdReadmeRoute
  '/_auth/$slug/_dash/': typeof AuthSlugDashIndexRoute
  '/_auth/$slug/_dash/deployments/$deploymentId': typeof AuthSlugDashDeploymentsDeploymentIdRouteRouteWithChildren
  '/_auth/$slug/_dash/deployments': typeof AuthSlugDashDeploymentsRouteWithChildren
  '/_auth/$slug/_dash/deployments/_list': typeof AuthSlugDashDeploymentsListRouteRouteWithChildren
  '/_auth/$slug/_dash/servers/$serverId': typeof AuthSlugDashServersServerIdRouteRouteWithChildren
  '/_auth/$slug/_dash/servers': typeof AuthSlugDashServersRouteWithChildren
  '/_auth/$slug/_dash/servers/_list': typeof AuthSlugDashServersListRouteRouteWithChildren
  '/_auth/$slug/_dash/servers/import': typeof AuthSlugDashServersImportRoute
  '/_auth/$slug/_dash/servers/new': typeof AuthSlugDashServersNewRoute
  '/_auth/$slug/_dash/settings/github': typeof AuthSlugDashSettingsGithubRoute
  '/_auth/$slug/_dash/settings/webhooks': typeof AuthSlugDashSettingsWebhooksRoute
  '/_auth/$slug/_dash/settings/': typeof AuthSlugDashSettingsIndexRoute
  '/_auth/$slug/_dash/servers/$serverId/_detail': typeof AuthSlugDashServersServerIdDetailRouteRouteWithChildren
  '/_auth/$slug/_dash/deployments/$deploymentId/logs': typeof AuthSlugDashDeploymentsDeploymentIdLogsRoute
  '/_auth/$slug/_dash/deployments/_list/preview': typeof AuthSlugDashDeploymentsListPreviewRoute
  '/_auth/$slug/_dash/deployments/_list/production': typeof AuthSlugDashDeploymentsListProductionRoute
  '/_auth/$slug/_dash/servers/$serverId/deploy': typeof AuthSlugDashServersServerIdDeployRoute
  '/_auth/$slug/_dash/servers/_list/private': typeof AuthSlugDashServersListPrivateRoute
  '/_auth/$slug/_dash/servers/_list/public': typeof AuthSlugDashServersListPublicRoute
  '/_auth/$slug/_dash/deployments/$deploymentId/': typeof AuthSlugDashDeploymentsDeploymentIdIndexRoute
  '/_auth/$slug/_dash/deployments/_list/': typeof AuthSlugDashDeploymentsListIndexRoute
  '/_auth/$slug/_dash/servers/_list/': typeof AuthSlugDashServersListIndexRoute
  '/_auth/$slug/_dash/servers/$serverId/_detail/deployments': typeof AuthSlugDashServersServerIdDetailDeploymentsRouteRouteWithChildren
  '/_auth/$slug/_dash/servers/$serverId/_detail/analytics': typeof AuthSlugDashServersServerIdDetailAnalyticsRoute
  '/_auth/$slug/_dash/servers/$serverId/_detail/readme': typeof AuthSlugDashServersServerIdDetailReadmeRoute
  '/_auth/$slug/_dash/servers/$serverId/_detail/settings': typeof AuthSlugDashServersServerIdDetailSettingsRoute
  '/_auth/$slug/_dash/servers/$serverId/_detail/': typeof AuthSlugDashServersServerIdDetailIndexRoute
  '/_auth/$slug/_dash/servers/$serverId/_detail/deployments/preview': typeof AuthSlugDashServersServerIdDetailDeploymentsPreviewRoute
  '/_auth/$slug/_dash/servers/$serverId/_detail/deployments/production': typeof AuthSlugDashServersServerIdDetailDeploymentsProductionRoute
  '/_auth/$slug/_dash/servers/$serverId/_detail/deployments/': typeof AuthSlugDashServersServerIdDetailDeploymentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/$slug'
    | '/github/installed'
    | '/'
    | '/api/auth/$'
    | '/api/github/callback'
    | '/api/github/installs'
    | '/api/github/repos'
    | '/api/sync/v1'
    | '/$slug/settings'
    | '/api/servers/$serverId/readme'
    | '/$slug/'
    | '/$slug/deployments/$deploymentId'
    | '/$slug/deployments'
    | '/$slug/servers/$serverId'
    | '/$slug/servers'
    | '/$slug/servers/import'
    | '/$slug/servers/new'
    | '/$slug/settings/github'
    | '/$slug/settings/webhooks'
    | '/$slug/settings/'
    | '/$slug/deployments/$deploymentId/logs'
    | '/$slug/deployments/preview'
    | '/$slug/deployments/production'
    | '/$slug/servers/$serverId/deploy'
    | '/$slug/servers/private'
    | '/$slug/servers/public'
    | '/$slug/deployments/$deploymentId/'
    | '/$slug/deployments/'
    | '/$slug/servers/'
    | '/$slug/servers/$serverId/deployments'
    | '/$slug/servers/$serverId/analytics'
    | '/$slug/servers/$serverId/readme'
    | '/$slug/servers/$serverId/settings'
    | '/$slug/servers/$serverId/'
    | '/$slug/servers/$serverId/deployments/preview'
    | '/$slug/servers/$serverId/deployments/production'
    | '/$slug/servers/$serverId/deployments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$slug'
    | '/github/installed'
    | '/'
    | '/api/auth/$'
    | '/api/github/callback'
    | '/api/github/installs'
    | '/api/github/repos'
    | '/api/sync/v1'
    | '/api/servers/$serverId/readme'
    | '/$slug/deployments'
    | '/$slug/servers/$serverId'
    | '/$slug/servers'
    | '/$slug/servers/import'
    | '/$slug/servers/new'
    | '/$slug/settings/github'
    | '/$slug/settings/webhooks'
    | '/$slug/settings'
    | '/$slug/deployments/$deploymentId/logs'
    | '/$slug/deployments/preview'
    | '/$slug/deployments/production'
    | '/$slug/servers/$serverId/deploy'
    | '/$slug/servers/private'
    | '/$slug/servers/public'
    | '/$slug/deployments/$deploymentId'
    | '/$slug/servers/$serverId/analytics'
    | '/$slug/servers/$serverId/readme'
    | '/$slug/servers/$serverId/settings'
    | '/$slug/servers/$serverId/deployments/preview'
    | '/$slug/servers/$serverId/deployments/production'
    | '/$slug/servers/$serverId/deployments'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/$slug'
    | '/github/installed'
    | '/_auth/'
    | '/_auth/$slug/_dash'
    | '/api/auth/$'
    | '/api/github/callback'
    | '/api/github/installs'
    | '/api/github/repos'
    | '/api/sync/v1'
    | '/_auth/$slug/_dash/settings'
    | '/api/servers/$serverId/readme'
    | '/_auth/$slug/_dash/'
    | '/_auth/$slug/_dash/deployments/$deploymentId'
    | '/_auth/$slug/_dash/deployments'
    | '/_auth/$slug/_dash/deployments/_list'
    | '/_auth/$slug/_dash/servers/$serverId'
    | '/_auth/$slug/_dash/servers'
    | '/_auth/$slug/_dash/servers/_list'
    | '/_auth/$slug/_dash/servers/import'
    | '/_auth/$slug/_dash/servers/new'
    | '/_auth/$slug/_dash/settings/github'
    | '/_auth/$slug/_dash/settings/webhooks'
    | '/_auth/$slug/_dash/settings/'
    | '/_auth/$slug/_dash/servers/$serverId/_detail'
    | '/_auth/$slug/_dash/deployments/$deploymentId/logs'
    | '/_auth/$slug/_dash/deployments/_list/preview'
    | '/_auth/$slug/_dash/deployments/_list/production'
    | '/_auth/$slug/_dash/servers/$serverId/deploy'
    | '/_auth/$slug/_dash/servers/_list/private'
    | '/_auth/$slug/_dash/servers/_list/public'
    | '/_auth/$slug/_dash/deployments/$deploymentId/'
    | '/_auth/$slug/_dash/deployments/_list/'
    | '/_auth/$slug/_dash/servers/_list/'
    | '/_auth/$slug/_dash/servers/$serverId/_detail/deployments'
    | '/_auth/$slug/_dash/servers/$serverId/_detail/analytics'
    | '/_auth/$slug/_dash/servers/$serverId/_detail/readme'
    | '/_auth/$slug/_dash/servers/$serverId/_detail/settings'
    | '/_auth/$slug/_dash/servers/$serverId/_detail/'
    | '/_auth/$slug/_dash/servers/$serverId/_detail/deployments/preview'
    | '/_auth/$slug/_dash/servers/$serverId/_detail/deployments/production'
    | '/_auth/$slug/_dash/servers/$serverId/_detail/deployments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  GithubInstalledRoute: typeof GithubInstalledRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGithubCallbackRoute: typeof ApiGithubCallbackRoute
  ApiGithubInstallsRoute: typeof ApiGithubInstallsRoute
  ApiGithubReposRoute: typeof ApiGithubReposRoute
  ApiSyncV1Route: typeof ApiSyncV1Route
  ApiServersServerIdReadmeRoute: typeof ApiServersServerIdReadmeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/github/installed': {
      id: '/github/installed'
      path: '/github/installed'
      fullPath: '/github/installed'
      preLoaderRoute: typeof GithubInstalledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/$slug': {
      id: '/_auth/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof AuthSlugRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/sync/v1': {
      id: '/api/sync/v1'
      path: '/api/sync/v1'
      fullPath: '/api/sync/v1'
      preLoaderRoute: typeof ApiSyncV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/repos': {
      id: '/api/github/repos'
      path: '/api/github/repos'
      fullPath: '/api/github/repos'
      preLoaderRoute: typeof ApiGithubReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/installs': {
      id: '/api/github/installs'
      path: '/api/github/installs'
      fullPath: '/api/github/installs'
      preLoaderRoute: typeof ApiGithubInstallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/callback': {
      id: '/api/github/callback'
      path: '/api/github/callback'
      fullPath: '/api/github/callback'
      preLoaderRoute: typeof ApiGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/$slug/_dash': {
      id: '/_auth/$slug/_dash'
      path: ''
      fullPath: '/$slug'
      preLoaderRoute: typeof AuthSlugDashRouteRouteImport
      parentRoute: typeof AuthSlugRouteRoute
    }
    '/_auth/$slug/_dash/servers': {
      id: '/_auth/$slug/_dash/servers'
      path: '/servers'
      fullPath: '/$slug/servers'
      preLoaderRoute: typeof AuthSlugDashServersRouteImport
      parentRoute: typeof AuthSlugDashRouteRoute
    }
    '/_auth/$slug/_dash/deployments': {
      id: '/_auth/$slug/_dash/deployments'
      path: '/deployments'
      fullPath: '/$slug/deployments'
      preLoaderRoute: typeof AuthSlugDashDeploymentsRouteImport
      parentRoute: typeof AuthSlugDashRouteRoute
    }
    '/_auth/$slug/_dash/': {
      id: '/_auth/$slug/_dash/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof AuthSlugDashIndexRouteImport
      parentRoute: typeof AuthSlugDashRouteRoute
    }
    '/api/servers/$serverId/readme': {
      id: '/api/servers/$serverId/readme'
      path: '/api/servers/$serverId/readme'
      fullPath: '/api/servers/$serverId/readme'
      preLoaderRoute: typeof ApiServersServerIdReadmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/$slug/_dash/settings': {
      id: '/_auth/$slug/_dash/settings'
      path: '/settings'
      fullPath: '/$slug/settings'
      preLoaderRoute: typeof AuthSlugDashSettingsRouteRouteImport
      parentRoute: typeof AuthSlugDashRouteRoute
    }
    '/_auth/$slug/_dash/settings/': {
      id: '/_auth/$slug/_dash/settings/'
      path: '/'
      fullPath: '/$slug/settings/'
      preLoaderRoute: typeof AuthSlugDashSettingsIndexRouteImport
      parentRoute: typeof AuthSlugDashSettingsRouteRoute
    }
    '/_auth/$slug/_dash/settings/webhooks': {
      id: '/_auth/$slug/_dash/settings/webhooks'
      path: '/webhooks'
      fullPath: '/$slug/settings/webhooks'
      preLoaderRoute: typeof AuthSlugDashSettingsWebhooksRouteImport
      parentRoute: typeof AuthSlugDashSettingsRouteRoute
    }
    '/_auth/$slug/_dash/settings/github': {
      id: '/_auth/$slug/_dash/settings/github'
      path: '/github'
      fullPath: '/$slug/settings/github'
      preLoaderRoute: typeof AuthSlugDashSettingsGithubRouteImport
      parentRoute: typeof AuthSlugDashSettingsRouteRoute
    }
    '/_auth/$slug/_dash/servers/new': {
      id: '/_auth/$slug/_dash/servers/new'
      path: '/new'
      fullPath: '/$slug/servers/new'
      preLoaderRoute: typeof AuthSlugDashServersNewRouteImport
      parentRoute: typeof AuthSlugDashServersRoute
    }
    '/_auth/$slug/_dash/servers/import': {
      id: '/_auth/$slug/_dash/servers/import'
      path: '/import'
      fullPath: '/$slug/servers/import'
      preLoaderRoute: typeof AuthSlugDashServersImportRouteImport
      parentRoute: typeof AuthSlugDashServersRoute
    }
    '/_auth/$slug/_dash/servers/_list': {
      id: '/_auth/$slug/_dash/servers/_list'
      path: '/servers'
      fullPath: '/$slug/servers'
      preLoaderRoute: typeof AuthSlugDashServersListRouteRouteImport
      parentRoute: typeof AuthSlugDashServersRoute
    }
    '/_auth/$slug/_dash/servers/$serverId': {
      id: '/_auth/$slug/_dash/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/$slug/servers/$serverId'
      preLoaderRoute: typeof AuthSlugDashServersServerIdRouteRouteImport
      parentRoute: typeof AuthSlugDashRouteRoute
    }
    '/_auth/$slug/_dash/deployments/_list': {
      id: '/_auth/$slug/_dash/deployments/_list'
      path: '/deployments'
      fullPath: '/$slug/deployments'
      preLoaderRoute: typeof AuthSlugDashDeploymentsListRouteRouteImport
      parentRoute: typeof AuthSlugDashDeploymentsRoute
    }
    '/_auth/$slug/_dash/deployments/$deploymentId': {
      id: '/_auth/$slug/_dash/deployments/$deploymentId'
      path: '/deployments/$deploymentId'
      fullPath: '/$slug/deployments/$deploymentId'
      preLoaderRoute: typeof AuthSlugDashDeploymentsDeploymentIdRouteRouteImport
      parentRoute: typeof AuthSlugDashRouteRoute
    }
    '/_auth/$slug/_dash/servers/_list/': {
      id: '/_auth/$slug/_dash/servers/_list/'
      path: '/'
      fullPath: '/$slug/servers/'
      preLoaderRoute: typeof AuthSlugDashServersListIndexRouteImport
      parentRoute: typeof AuthSlugDashServersListRouteRoute
    }
    '/_auth/$slug/_dash/deployments/_list/': {
      id: '/_auth/$slug/_dash/deployments/_list/'
      path: '/'
      fullPath: '/$slug/deployments/'
      preLoaderRoute: typeof AuthSlugDashDeploymentsListIndexRouteImport
      parentRoute: typeof AuthSlugDashDeploymentsListRouteRoute
    }
    '/_auth/$slug/_dash/deployments/$deploymentId/': {
      id: '/_auth/$slug/_dash/deployments/$deploymentId/'
      path: '/'
      fullPath: '/$slug/deployments/$deploymentId/'
      preLoaderRoute: typeof AuthSlugDashDeploymentsDeploymentIdIndexRouteImport
      parentRoute: typeof AuthSlugDashDeploymentsDeploymentIdRouteRoute
    }
    '/_auth/$slug/_dash/servers/_list/public': {
      id: '/_auth/$slug/_dash/servers/_list/public'
      path: '/public'
      fullPath: '/$slug/servers/public'
      preLoaderRoute: typeof AuthSlugDashServersListPublicRouteImport
      parentRoute: typeof AuthSlugDashServersListRouteRoute
    }
    '/_auth/$slug/_dash/servers/_list/private': {
      id: '/_auth/$slug/_dash/servers/_list/private'
      path: '/private'
      fullPath: '/$slug/servers/private'
      preLoaderRoute: typeof AuthSlugDashServersListPrivateRouteImport
      parentRoute: typeof AuthSlugDashServersListRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/deploy': {
      id: '/_auth/$slug/_dash/servers/$serverId/deploy'
      path: '/deploy'
      fullPath: '/$slug/servers/$serverId/deploy'
      preLoaderRoute: typeof AuthSlugDashServersServerIdDeployRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdRouteRoute
    }
    '/_auth/$slug/_dash/deployments/_list/production': {
      id: '/_auth/$slug/_dash/deployments/_list/production'
      path: '/production'
      fullPath: '/$slug/deployments/production'
      preLoaderRoute: typeof AuthSlugDashDeploymentsListProductionRouteImport
      parentRoute: typeof AuthSlugDashDeploymentsListRouteRoute
    }
    '/_auth/$slug/_dash/deployments/_list/preview': {
      id: '/_auth/$slug/_dash/deployments/_list/preview'
      path: '/preview'
      fullPath: '/$slug/deployments/preview'
      preLoaderRoute: typeof AuthSlugDashDeploymentsListPreviewRouteImport
      parentRoute: typeof AuthSlugDashDeploymentsListRouteRoute
    }
    '/_auth/$slug/_dash/deployments/$deploymentId/logs': {
      id: '/_auth/$slug/_dash/deployments/$deploymentId/logs'
      path: '/logs'
      fullPath: '/$slug/deployments/$deploymentId/logs'
      preLoaderRoute: typeof AuthSlugDashDeploymentsDeploymentIdLogsRouteImport
      parentRoute: typeof AuthSlugDashDeploymentsDeploymentIdRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/_detail': {
      id: '/_auth/$slug/_dash/servers/$serverId/_detail'
      path: ''
      fullPath: '/$slug/servers/$serverId'
      preLoaderRoute: typeof AuthSlugDashServersServerIdDetailRouteRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/_detail/': {
      id: '/_auth/$slug/_dash/servers/$serverId/_detail/'
      path: '/'
      fullPath: '/$slug/servers/$serverId/'
      preLoaderRoute: typeof AuthSlugDashServersServerIdDetailIndexRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdDetailRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/_detail/settings': {
      id: '/_auth/$slug/_dash/servers/$serverId/_detail/settings'
      path: '/settings'
      fullPath: '/$slug/servers/$serverId/settings'
      preLoaderRoute: typeof AuthSlugDashServersServerIdDetailSettingsRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdDetailRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/_detail/readme': {
      id: '/_auth/$slug/_dash/servers/$serverId/_detail/readme'
      path: '/readme'
      fullPath: '/$slug/servers/$serverId/readme'
      preLoaderRoute: typeof AuthSlugDashServersServerIdDetailReadmeRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdDetailRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/_detail/analytics': {
      id: '/_auth/$slug/_dash/servers/$serverId/_detail/analytics'
      path: '/analytics'
      fullPath: '/$slug/servers/$serverId/analytics'
      preLoaderRoute: typeof AuthSlugDashServersServerIdDetailAnalyticsRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdDetailRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/_detail/deployments': {
      id: '/_auth/$slug/_dash/servers/$serverId/_detail/deployments'
      path: '/deployments'
      fullPath: '/$slug/servers/$serverId/deployments'
      preLoaderRoute: typeof AuthSlugDashServersServerIdDetailDeploymentsRouteRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdDetailRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/_detail/deployments/': {
      id: '/_auth/$slug/_dash/servers/$serverId/_detail/deployments/'
      path: '/'
      fullPath: '/$slug/servers/$serverId/deployments/'
      preLoaderRoute: typeof AuthSlugDashServersServerIdDetailDeploymentsIndexRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdDetailDeploymentsRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/_detail/deployments/production': {
      id: '/_auth/$slug/_dash/servers/$serverId/_detail/deployments/production'
      path: '/production'
      fullPath: '/$slug/servers/$serverId/deployments/production'
      preLoaderRoute: typeof AuthSlugDashServersServerIdDetailDeploymentsProductionRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdDetailDeploymentsRouteRoute
    }
    '/_auth/$slug/_dash/servers/$serverId/_detail/deployments/preview': {
      id: '/_auth/$slug/_dash/servers/$serverId/_detail/deployments/preview'
      path: '/preview'
      fullPath: '/$slug/servers/$serverId/deployments/preview'
      preLoaderRoute: typeof AuthSlugDashServersServerIdDetailDeploymentsPreviewRouteImport
      parentRoute: typeof AuthSlugDashServersServerIdDetailDeploymentsRouteRoute
    }
  }
}

interface AuthSlugDashSettingsRouteRouteChildren {
  AuthSlugDashSettingsGithubRoute: typeof AuthSlugDashSettingsGithubRoute
  AuthSlugDashSettingsWebhooksRoute: typeof AuthSlugDashSettingsWebhooksRoute
  AuthSlugDashSettingsIndexRoute: typeof AuthSlugDashSettingsIndexRoute
}

const AuthSlugDashSettingsRouteRouteChildren: AuthSlugDashSettingsRouteRouteChildren =
  {
    AuthSlugDashSettingsGithubRoute: AuthSlugDashSettingsGithubRoute,
    AuthSlugDashSettingsWebhooksRoute: AuthSlugDashSettingsWebhooksRoute,
    AuthSlugDashSettingsIndexRoute: AuthSlugDashSettingsIndexRoute,
  }

const AuthSlugDashSettingsRouteRouteWithChildren =
  AuthSlugDashSettingsRouteRoute._addFileChildren(
    AuthSlugDashSettingsRouteRouteChildren,
  )

interface AuthSlugDashDeploymentsDeploymentIdRouteRouteChildren {
  AuthSlugDashDeploymentsDeploymentIdLogsRoute: typeof AuthSlugDashDeploymentsDeploymentIdLogsRoute
  AuthSlugDashDeploymentsDeploymentIdIndexRoute: typeof AuthSlugDashDeploymentsDeploymentIdIndexRoute
}

const AuthSlugDashDeploymentsDeploymentIdRouteRouteChildren: AuthSlugDashDeploymentsDeploymentIdRouteRouteChildren =
  {
    AuthSlugDashDeploymentsDeploymentIdLogsRoute:
      AuthSlugDashDeploymentsDeploymentIdLogsRoute,
    AuthSlugDashDeploymentsDeploymentIdIndexRoute:
      AuthSlugDashDeploymentsDeploymentIdIndexRoute,
  }

const AuthSlugDashDeploymentsDeploymentIdRouteRouteWithChildren =
  AuthSlugDashDeploymentsDeploymentIdRouteRoute._addFileChildren(
    AuthSlugDashDeploymentsDeploymentIdRouteRouteChildren,
  )

interface AuthSlugDashDeploymentsListRouteRouteChildren {
  AuthSlugDashDeploymentsListPreviewRoute: typeof AuthSlugDashDeploymentsListPreviewRoute
  AuthSlugDashDeploymentsListProductionRoute: typeof AuthSlugDashDeploymentsListProductionRoute
  AuthSlugDashDeploymentsListIndexRoute: typeof AuthSlugDashDeploymentsListIndexRoute
}

const AuthSlugDashDeploymentsListRouteRouteChildren: AuthSlugDashDeploymentsListRouteRouteChildren =
  {
    AuthSlugDashDeploymentsListPreviewRoute:
      AuthSlugDashDeploymentsListPreviewRoute,
    AuthSlugDashDeploymentsListProductionRoute:
      AuthSlugDashDeploymentsListProductionRoute,
    AuthSlugDashDeploymentsListIndexRoute:
      AuthSlugDashDeploymentsListIndexRoute,
  }

const AuthSlugDashDeploymentsListRouteRouteWithChildren =
  AuthSlugDashDeploymentsListRouteRoute._addFileChildren(
    AuthSlugDashDeploymentsListRouteRouteChildren,
  )

interface AuthSlugDashDeploymentsRouteChildren {
  AuthSlugDashDeploymentsListRouteRoute: typeof AuthSlugDashDeploymentsListRouteRouteWithChildren
}

const AuthSlugDashDeploymentsRouteChildren: AuthSlugDashDeploymentsRouteChildren =
  {
    AuthSlugDashDeploymentsListRouteRoute:
      AuthSlugDashDeploymentsListRouteRouteWithChildren,
  }

const AuthSlugDashDeploymentsRouteWithChildren =
  AuthSlugDashDeploymentsRoute._addFileChildren(
    AuthSlugDashDeploymentsRouteChildren,
  )

interface AuthSlugDashServersServerIdDetailDeploymentsRouteRouteChildren {
  AuthSlugDashServersServerIdDetailDeploymentsPreviewRoute: typeof AuthSlugDashServersServerIdDetailDeploymentsPreviewRoute
  AuthSlugDashServersServerIdDetailDeploymentsProductionRoute: typeof AuthSlugDashServersServerIdDetailDeploymentsProductionRoute
  AuthSlugDashServersServerIdDetailDeploymentsIndexRoute: typeof AuthSlugDashServersServerIdDetailDeploymentsIndexRoute
}

const AuthSlugDashServersServerIdDetailDeploymentsRouteRouteChildren: AuthSlugDashServersServerIdDetailDeploymentsRouteRouteChildren =
  {
    AuthSlugDashServersServerIdDetailDeploymentsPreviewRoute:
      AuthSlugDashServersServerIdDetailDeploymentsPreviewRoute,
    AuthSlugDashServersServerIdDetailDeploymentsProductionRoute:
      AuthSlugDashServersServerIdDetailDeploymentsProductionRoute,
    AuthSlugDashServersServerIdDetailDeploymentsIndexRoute:
      AuthSlugDashServersServerIdDetailDeploymentsIndexRoute,
  }

const AuthSlugDashServersServerIdDetailDeploymentsRouteRouteWithChildren =
  AuthSlugDashServersServerIdDetailDeploymentsRouteRoute._addFileChildren(
    AuthSlugDashServersServerIdDetailDeploymentsRouteRouteChildren,
  )

interface AuthSlugDashServersServerIdDetailRouteRouteChildren {
  AuthSlugDashServersServerIdDetailDeploymentsRouteRoute: typeof AuthSlugDashServersServerIdDetailDeploymentsRouteRouteWithChildren
  AuthSlugDashServersServerIdDetailAnalyticsRoute: typeof AuthSlugDashServersServerIdDetailAnalyticsRoute
  AuthSlugDashServersServerIdDetailReadmeRoute: typeof AuthSlugDashServersServerIdDetailReadmeRoute
  AuthSlugDashServersServerIdDetailSettingsRoute: typeof AuthSlugDashServersServerIdDetailSettingsRoute
  AuthSlugDashServersServerIdDetailIndexRoute: typeof AuthSlugDashServersServerIdDetailIndexRoute
}

const AuthSlugDashServersServerIdDetailRouteRouteChildren: AuthSlugDashServersServerIdDetailRouteRouteChildren =
  {
    AuthSlugDashServersServerIdDetailDeploymentsRouteRoute:
      AuthSlugDashServersServerIdDetailDeploymentsRouteRouteWithChildren,
    AuthSlugDashServersServerIdDetailAnalyticsRoute:
      AuthSlugDashServersServerIdDetailAnalyticsRoute,
    AuthSlugDashServersServerIdDetailReadmeRoute:
      AuthSlugDashServersServerIdDetailReadmeRoute,
    AuthSlugDashServersServerIdDetailSettingsRoute:
      AuthSlugDashServersServerIdDetailSettingsRoute,
    AuthSlugDashServersServerIdDetailIndexRoute:
      AuthSlugDashServersServerIdDetailIndexRoute,
  }

const AuthSlugDashServersServerIdDetailRouteRouteWithChildren =
  AuthSlugDashServersServerIdDetailRouteRoute._addFileChildren(
    AuthSlugDashServersServerIdDetailRouteRouteChildren,
  )

interface AuthSlugDashServersServerIdRouteRouteChildren {
  AuthSlugDashServersServerIdDetailRouteRoute: typeof AuthSlugDashServersServerIdDetailRouteRouteWithChildren
  AuthSlugDashServersServerIdDeployRoute: typeof AuthSlugDashServersServerIdDeployRoute
}

const AuthSlugDashServersServerIdRouteRouteChildren: AuthSlugDashServersServerIdRouteRouteChildren =
  {
    AuthSlugDashServersServerIdDetailRouteRoute:
      AuthSlugDashServersServerIdDetailRouteRouteWithChildren,
    AuthSlugDashServersServerIdDeployRoute:
      AuthSlugDashServersServerIdDeployRoute,
  }

const AuthSlugDashServersServerIdRouteRouteWithChildren =
  AuthSlugDashServersServerIdRouteRoute._addFileChildren(
    AuthSlugDashServersServerIdRouteRouteChildren,
  )

interface AuthSlugDashServersListRouteRouteChildren {
  AuthSlugDashServersListPrivateRoute: typeof AuthSlugDashServersListPrivateRoute
  AuthSlugDashServersListPublicRoute: typeof AuthSlugDashServersListPublicRoute
  AuthSlugDashServersListIndexRoute: typeof AuthSlugDashServersListIndexRoute
}

const AuthSlugDashServersListRouteRouteChildren: AuthSlugDashServersListRouteRouteChildren =
  {
    AuthSlugDashServersListPrivateRoute: AuthSlugDashServersListPrivateRoute,
    AuthSlugDashServersListPublicRoute: AuthSlugDashServersListPublicRoute,
    AuthSlugDashServersListIndexRoute: AuthSlugDashServersListIndexRoute,
  }

const AuthSlugDashServersListRouteRouteWithChildren =
  AuthSlugDashServersListRouteRoute._addFileChildren(
    AuthSlugDashServersListRouteRouteChildren,
  )

interface AuthSlugDashServersRouteChildren {
  AuthSlugDashServersListRouteRoute: typeof AuthSlugDashServersListRouteRouteWithChildren
  AuthSlugDashServersImportRoute: typeof AuthSlugDashServersImportRoute
  AuthSlugDashServersNewRoute: typeof AuthSlugDashServersNewRoute
}

const AuthSlugDashServersRouteChildren: AuthSlugDashServersRouteChildren = {
  AuthSlugDashServersListRouteRoute:
    AuthSlugDashServersListRouteRouteWithChildren,
  AuthSlugDashServersImportRoute: AuthSlugDashServersImportRoute,
  AuthSlugDashServersNewRoute: AuthSlugDashServersNewRoute,
}

const AuthSlugDashServersRouteWithChildren =
  AuthSlugDashServersRoute._addFileChildren(AuthSlugDashServersRouteChildren)

interface AuthSlugDashRouteRouteChildren {
  AuthSlugDashSettingsRouteRoute: typeof AuthSlugDashSettingsRouteRouteWithChildren
  AuthSlugDashIndexRoute: typeof AuthSlugDashIndexRoute
  AuthSlugDashDeploymentsDeploymentIdRouteRoute: typeof AuthSlugDashDeploymentsDeploymentIdRouteRouteWithChildren
  AuthSlugDashDeploymentsRoute: typeof AuthSlugDashDeploymentsRouteWithChildren
  AuthSlugDashServersServerIdRouteRoute: typeof AuthSlugDashServersServerIdRouteRouteWithChildren
  AuthSlugDashServersRoute: typeof AuthSlugDashServersRouteWithChildren
}

const AuthSlugDashRouteRouteChildren: AuthSlugDashRouteRouteChildren = {
  AuthSlugDashSettingsRouteRoute: AuthSlugDashSettingsRouteRouteWithChildren,
  AuthSlugDashIndexRoute: AuthSlugDashIndexRoute,
  AuthSlugDashDeploymentsDeploymentIdRouteRoute:
    AuthSlugDashDeploymentsDeploymentIdRouteRouteWithChildren,
  AuthSlugDashDeploymentsRoute: AuthSlugDashDeploymentsRouteWithChildren,
  AuthSlugDashServersServerIdRouteRoute:
    AuthSlugDashServersServerIdRouteRouteWithChildren,
  AuthSlugDashServersRoute: AuthSlugDashServersRouteWithChildren,
}

const AuthSlugDashRouteRouteWithChildren =
  AuthSlugDashRouteRoute._addFileChildren(AuthSlugDashRouteRouteChildren)

interface AuthSlugRouteRouteChildren {
  AuthSlugDashRouteRoute: typeof AuthSlugDashRouteRouteWithChildren
}

const AuthSlugRouteRouteChildren: AuthSlugRouteRouteChildren = {
  AuthSlugDashRouteRoute: AuthSlugDashRouteRouteWithChildren,
}

const AuthSlugRouteRouteWithChildren = AuthSlugRouteRoute._addFileChildren(
  AuthSlugRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSlugRouteRoute: typeof AuthSlugRouteRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSlugRouteRoute: AuthSlugRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  GithubInstalledRoute: GithubInstalledRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGithubCallbackRoute: ApiGithubCallbackRoute,
  ApiGithubInstallsRoute: ApiGithubInstallsRoute,
  ApiGithubReposRoute: ApiGithubReposRoute,
  ApiSyncV1Route: ApiSyncV1Route,
  ApiServersServerIdReadmeRoute: ApiServersServerIdReadmeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
